(function(){
'use strict';
const DETAILS=window.KAYAS_EN_DETAILS||{};
const arch={'A-01':'This is a building-corner zone. The west and south sides are exterior building boundaries; no continuation room, corridor, door, or opening may be created in either direction.','TR-01':'This is the 5 m service terrace outside the east boundary of the enclosed floor.'};
const generic='The master numbered layout is authoritative. No room, corridor, door, opening or adjacent space may be invented.';
const set=(id,v)=>{const e=typeof id==='string'?document.getElementById(id):id;if(e)e.textContent=v};
const ZONE_VIS_KEY='kayas_zone_details_visible';
let zoneDetailsVisible=true;
function readZonePref(){try{const v=sessionStorage.getItem(ZONE_VIS_KEY);if(v!==null)zoneDetailsVisible=v!=='0'}catch(_){}}
function saveZonePref(){try{sessionStorage.setItem(ZONE_VIS_KEY,zoneDetailsVisible?'1':'0')}catch(_){}}
function applyZoneVisibility(forceShow=false){const zi=document.getElementById('zoneInfo'),show=document.getElementById('zonePanelShow');if(!zi)return;if(zoneDetailsVisible){zi.classList.remove('kayas-zone-manual-hidden');if(forceShow)zi.classList.remove('hidden');document.body.classList.remove('kayas-zone-details-hidden');if(show)show.setAttribute('aria-expanded','true')}else{zi.classList.add('kayas-zone-manual-hidden');document.body.classList.add('kayas-zone-details-hidden');if(show)show.setAttribute('aria-expanded','false')}}
function installZoneToggle(){const zi=document.getElementById('zoneInfo');if(!zi)return;document.querySelectorAll('.nav button').forEach(b=>{if(/zone details/i.test((b.textContent||'').trim()))b.remove()});if(!document.getElementById('zonePanelHide')){const b=document.createElement('button');b.id='zonePanelHide';b.type='button';b.title='Hide Zone Details';b.setAttribute('aria-label','Hide Zone Details');b.textContent='×';zi.appendChild(b);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();zoneDetailsVisible=false;saveZonePref();applyZoneVisibility()})}if(!document.getElementById('zonePanelShow')){const b=document.createElement('button');b.id='zonePanelShow';b.type='button';b.textContent='Zone Details';b.setAttribute('aria-controls','zoneInfo');document.body.appendChild(b);b.addEventListener('click',()=>{zoneDetailsVisible=true;saveZonePref();applyZoneVisibility(true)})}if(!document.getElementById('zoneDetailsToggleStyle')){const s=document.createElement('style');s.id='zoneDetailsToggleStyle';s.textContent='#zoneInfo.kayas-zone-manual-hidden{display:none!important}#zonePanelHide{position:absolute;right:10px;top:9px;z-index:4;width:27px;height:27px;border:1px solid #466475;border-radius:8px;background:#102936;color:#dff3fb;font:800 17px/22px Segoe UI,Arial,sans-serif;cursor:pointer}#zonePanelHide:hover{border-color:#6ed8ff;background:#17445a}#zonePanelShow{position:absolute;z-index:25;right:0;top:50%;transform:translateY(-50%);border:1px solid #466475;border-right:0;border-radius:10px 0 0 10px;background:rgba(8,24,34,.95);color:#dff3fb;padding:10px 8px;writing-mode:vertical-rl;font:800 9px Segoe UI,Arial,sans-serif;letter-spacing:.08em;cursor:pointer;box-shadow:0 8px 24px #0005;display:none}body.kayas-zone-details-hidden #zonePanelShow{display:block}';document.head.appendChild(s)}applyZoneVisibility()}
function patchStatic(){document.documentElement.lang='en';document.title='KAYAS · 3rd Floor Zone Review';set(document.querySelector('.brand b'),'KAYAS · 3rd Floor Zone Review');set(document.querySelector('.brand span'),'Integrated Data Center & Digital Services Platform');set(document.querySelector('#zoneInfo .eyebrow'),'ZONE DETAILS');const hs=[...document.querySelectorAll('#zoneInfo .zone-section h4')];if(hs[0])set(hs[0],'IMPORTANCE TO THE DATA CENTER');if(hs[1])set(hs[1],'WHY THIS ZONE IS REQUIRED');if(hs[2])set(hs[2],'ARCHITECTURAL BOUNDARY');set(document.querySelector('#zoneInfo .zone-note'),'Selected zone function, importance and architectural constraints.');set(document.querySelector('#landing .kicker'),'KAYAS · 3RD FLOOR REVIEW');set(document.querySelector('#landing h1'),'KAYAS · 3rd Floor Zone Review');const lp=document.querySelector('#landing .landing-card > p');if(lp)lp.textContent='Interactive review of the 41-zone third-floor architecture, data hall, operations, support areas and service terrace.';const zt=document.getElementById('zoneTitle');if(zt)set(zt,'KAYAS · 3rd Floor Zone Review');const st=document.getElementById('status');if(st)set(st,'206 IT CABINETS · 1,972 kW');const tips=document.querySelector('.tips');if(tips)tips.textContent='Walk: W/A/S/D or arrows · Look: hold mouse and drag · Overview: drag to orbit and use the mouse wheel to zoom.';document.querySelectorAll('#landing .baseline span').forEach(x=>{if(/No humans|No guided|Rev|build/i.test(x.textContent))x.remove()})}
function defaultZone(){set('zoneInfoTitle','Hover over a zone');set('zoneInfoSub','Selected zone information');set('zoneInfoDesc','Hover over a zone number in Overview to display its function. Click a label to pin the selection.');set('zoneInfoImportance','Select a zone to review why it matters to operations, security, customer experience or technical continuity.');set('zoneInfoWhy','Select a zone to review why this function is maintained as a distinct room or controlled area.');set('zoneInfoArch',generic);const m=document.getElementById('zoneMedia');if(m)m.dataset.placeholder='No approved photorealistic visual has been assigned to this zone yet.';set('zoneMediaBadge','VISUAL PENDING');const p=document.getElementById('zonePinNote');if(p)p.innerHTML='<b>Hover:</b> preview · <b>Click:</b> pin selection'}
function showZone(id){const d=DETAILS[id];if(!d)return;set('zoneInfoTitle',id);set('zoneInfoSub',d.title);set('zoneInfoDesc',d.purpose);set('zoneInfoImportance',d.importance);set('zoneInfoWhy',d.why);set('zoneInfoArch',arch[id]||generic);const m=document.getElementById('zoneMedia');if(m){m.classList.add('empty');m.dataset.placeholder='No approved photorealistic visual has been assigned to this zone yet.'}set('zoneMediaBadge','VISUAL PENDING');const p=document.getElementById('zonePinNote');if(p)p.innerHTML='<b>Hover:</b> preview · <b>Click:</b> pin selection'}
function bindZoneEvents(){document.querySelectorAll('.zone-tag').forEach(el=>{if(el.dataset.kayasEnglishBound)return;el.dataset.kayasEnglishBound='1';const id=el.dataset.id;el.addEventListener('mouseenter',()=>queueMicrotask(()=>showZone(id)));el.addEventListener('focus',()=>queueMicrotask(()=>showZone(id)));el.addEventListener('click',()=>setTimeout(()=>showZone(id),0));el.addEventListener('mouseleave',()=>setTimeout(()=>{const pinned=document.querySelector('.zone-tag.pinned');if(pinned&&pinned.dataset.id)showZone(pinned.dataset.id);else defaultZone()},0))})}
function boot(){readZonePref();patchStatic();defaultZone();installZoneToggle();bindZoneEvents();const overlay=document.getElementById('zoneOverlay');if(overlay)new MutationObserver(bindZoneEvents).observe(overlay,{childList:true});setTimeout(()=>{const l=document.getElementById('landing');if(l)l.classList.add('hidden');try{overview()}catch(_){}bindZoneEvents();applyZoneVisibility()},100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();