(function(){
'use strict';
const guide=window.KAYAS_GUIDE;
if(!guide||!Array.isArray(guide.chapters)){document.getElementById('chapters').innerHTML='<section class="paper"><h1>Rehber verisi yüklenemedi</h1><p>guide-data.js erişimi kontrol edilmelidir.</p></section>';return;}
const P={
'01':{n:'Veri merkezi yatırımı; fiziksel tesis, enerji, bağlantı, IT platformları ve işletme kabiliyetinin birlikte ekonomik değer üretmesidir.',o:'Yatırımın başarısı yalnız bina veya kabinet sayısıyla değil; kullanılabilir güç, satılabilir kW/MW, doluluk, SLA ve müşteri talebiyle ölçülür.',t:'Colocation, enterprise/private DC, hyperscale/wholesale, cloud ve managed-service odaklı modeller.',c:'Enerji ve saha hazırlanır → MEP/IT altyapısı kurulur → kapasite müşteriye sözleşmeyle tahsis edilir → operasyon ve SLA üzerinden gelir üretilir.'},
'02':{n:'Veri merkezi fiziksel altyapısının geleneksel saha yapımı, mikro-modül veya prefabrik/fabrika üretimli modüllerle kurulması yaklaşımıdır.',o:'Kurulum süresi, standardizasyon, saha riski, CAPEX zamanlaması ve gelecekte kapasite ekleme biçimini doğrudan etkiler.',t:'Geleneksel site-built, mikro-modül/pod, prefabrik modüler (PFM), konteyner/complete module.',c:'Ortak güç-soğutma-fiber omurgasına tekrarlanabilir IT/MEP blokları bağlanır; talep büyüdükçe yeni modüller devreye alınır.'},
'03':{n:'Şebekeden IT rack’ine kadar elektriğin güvenli, seçici, ölçülebilir ve yedekli biçimde taşındığı tüm güç zinciridir.',o:'Veri merkezindeki en kritik süreklilik katmanıdır; güç yolu tasarımı satılabilir MW, Tier hedefi, bakım ve arıza etkisini belirler.',t:'OG/AG giriş, trafo, şalt, UPS, jeneratör, PDU/busway, rack PDU, A/B yol, koruma ve ölçüm.',c:'Şebeke enerjisi dönüştürülür ve dağıtılır; UPS kısa kesintileri köprüler, jeneratör uzun kesintide yükü devralır, A/B yollar kritik IT yükünü besler.'},
'04':{n:'UPS (Uninterruptible Power Supply), şebeke bozulması veya kesilmesi sırasında kritik IT yükünü kesintisiz besleyen güç elektroniği sistemidir.',o:'Milisaniye seviyesindeki kesintilerin sunucu, storage ve ağ cihazlarını durdurmasını önler; jeneratör devreye girene kadar ride-through sağlar.',t:'Static double-conversion UPS, modular UPS, rotary/DRUPS; enerji depolamada VRLA, Li-ion/LFP veya kinetik çözümler.',c:'Şebeke normalde UPS üzerinden yükü besler → kesintide inverter enerji depolamadan devam eder → jeneratör stabil hale gelince yük uzun süreli kaynağa aktarılır.'},
'05':{n:'UPS çıkışındaki gücü salon ve kabinet seviyesine taşıyan son-metre dağıtım katmanıdır.',o:'Rack yoğunluğu, A/B besleme, ölçüm, bakım esnekliği ve müşteri bazlı enerji faturalamasının temelidir.',t:'Floor PDU, overhead busway, tap-off box, rack PDU; basic, metered ve intelligent PDU.',c:'UPS/PDU çıkışı busway veya kabloyla dağıtılır → tap-off rack hattını besler → A/B rack PDU cihazın iki güç girişine enerji sağlar ve tüketimi ölçer.'},
'06':{n:'Elektrik enerjisinin batarya veya farklı depolama teknolojileriyle daha sonra kullanılmak üzere saklanmasıdır.',o:'UPS bataryası kısa süreli kesintisizliğe, BESS ise enerji esnekliği, peak shaving, yenilenebilir entegrasyonu ve bazı grid-use-case’lerine hizmet eder.',t:'VRLA, Li-ion/LFP UPS bataryaları; container/cabinet BESS, PCS/inverter, BMS ve EMS.',c:'Enerji depolama sistemi şarj olur → kontrol sistemi SoC ve güvenliği izler → ihtiyaç anında inverter üzerinden yük veya şebekeye kontrollü güç verir.'},
'07':{n:'Şebeke uzun süre kullanılamadığında kritik veri merkezi yüklerini besleyen motor-jeneratör tabanlı yedek güç katmanıdır.',o:'UPS’in kısa ride-through süresinden sonra iş sürekliliğini saatler veya yakıt tedariki sürdükçe devam ettirir.',t:'Diesel/gas genset, N+1 veya daha yüksek yedeklilik, ATS/STS/şalt entegrasyonu, merkezi veya day-tank yakıt sistemleri.',c:'Şebeke kaybolur → UPS yükü taşır → jeneratör start eder ve stabilize olur → şalt/ATS yükü jeneratöre geçirir → yakıt ve bakım planı sürekliliği sağlar.'},
'08':{n:'IT ekipmanının ürettiği ısının hava, su veya dielektrik sıvı üzerinden uzaklaştırılması ve çevreye atılması sürecidir.',o:'Enerji tüketimi, rack yoğunluğu, PUE/WUE, IT güvenilirliği ve AI/HPC kapasitesini belirleyen ana MEP sistemidir.',t:'In-row/CRAH/CRAC, air-cooled veya water-cooled chiller, dry/adiabatic cooling, rear-door HX, direct-to-chip + CDU, immersion.',c:'IT’den alınan ısı kapalı devreye aktarılır → eşanjör/chiller/heat-rejection sistemi ısıyı dışarı atar → soğutulmuş akışkan tekrar IT tarafına döner. Doğal su doğrudan IT devresine bağlanmaz.'},
'09':{n:'Veri merkezinin operatörlere, internete, müşterilere ve kendi rack/fabric yapısına yüksek hızlı optik bağlantı sağlayan fiziksel ve mantıksal ağ katmanıdır.',o:'Carrier çeşitliliği, düşük gecikme, cloud/colo ürünleri ve AI cluster fabric kapasitesi doğrudan fiber ve DC network tasarımına bağlıdır.',t:'MMR, carrier cross-connect, ODF, spine-leaf, EVPN/VXLAN, OOB yönetim; 100G/400G/800G ve gelişen 1.6T bağlantılar.',c:'Carrier fiberi bağımsız güzergâhlardan MMR’a gelir → cross-connect/core-spine katmanına bağlanır → leaf üzerinden compute/storage/rack’lere dağıtılır.'},
'10':{n:'Compute, storage ve network kaynaklarının yazılım, otomasyon ve self-service katmanıyla hizmet olarak sunulmasıdır.',o:'Fiziksel veri merkezi kapasitesini daha yüksek katma değerli IaaS/private cloud/managed hizmet gelirine dönüştürür.',t:'Private cloud, hybrid cloud, managed cloud; IaaS, PaaS, DBaaS, container/Kubernetes servisleri.',c:'Fiziksel kaynaklar sanallaştırılır/havuzlanır → cloud yönetimi katalog, quota ve workflow uygular → tenant portalı kaynak tüketir → metering/SLA üzerinden hizmet yönetilir.'},
'11':{n:'Müşterinin kendi IT ekipmanını veya dedicated altyapısını üçüncü taraf veri merkezinde güç, soğutma, bağlantı ve güvenlik hizmetleriyle barındırmasıdır.',o:'KAYAŞ’ın ilk ticari omurgalarından biridir; gelir rack sayısından çok contracted kW/MW, bağlantı, SLA ve ek hizmetlerden oluşur.',t:'Retail colo, wholesale/dedicated hall, cage/private suite, cross-connect, remote hands ve managed services.',c:'Müşteriye alan + güç kapasitesi + bağlantı tahsis edilir → tesis operasyonu çevresel ve enerji sürekliliğini sağlar → SLA, ölçüm ve destek hizmetleri faturalandırılır.'},
'12':{n:'Tiering veri merkezi altyapısının dayanıklılık/topoloji seviyesini; standartlar tasarım ve işletme gerekliliklerini; commissioning ise kurulan sistemlerin birlikte doğrulanmasını tanımlar.',o:'Yedekli ekipman satın almak tek başına güvenilir tesis üretmez; tasarım, kurulum, test ve operasyon kanıtının uçtan uca doğrulanması gerekir.',t:'Uptime Tier I–IV, ANSI/TIA-942, EN 50600/TS EN 50600 ailesi; FAT, SAT, IST, ORR ve acceptance süreçleri.',c:'Gereksinimler tasarıma çevrilir → ekipman ve sistemler FAT/SAT ile doğrulanır → Integrated Systems Test arıza ve geçiş senaryolarını sınar → operasyon ekibine kontrollü devredilir.'},
'13':{n:'Compute işlem gücünü, storage veriyi, HCI ise compute + software-defined storage + virtualization kaynaklarını ölçeklenebilir node’larda birleştirir.',o:'Cloud, sanallaştırma, veri tabanı, enterprise uygulamalar ve bazı AI iş yüklerinin performans, kapasite ve failure-domain temelini oluşturur.',t:'Rack server, blade/modular compute, SAN/NAS/object/SDS; 2/3/4+ node HCI cluster ve scale-out mimariler.',c:'Node’lardaki CPU/RAM/disk kaynakları yazılımla havuzlanır → sanallaştırma VM/container çalıştırır → veri node’lara dağıtılır ve replike edilir → yeni node eklenerek kapasite büyür.'},
'14':{n:'Sanallaştırma fiziksel donanım kaynaklarını mantıksal iş yüklerine ayırır; yedeklilik arıza etkisini sınırlar; büyüme ise kapasitenin kontrollü artırılmasıdır.',o:'Donanım arızası, bakım veya talep artışında hizmetin kesilmeden sürmesini ve kaynakların daha verimli kullanılmasını sağlar.',t:'Hypervisor, VM/container, HA cluster, live migration, replication, scale-up/scale-out, availability zone ve DR.',c:'İş yükleri kaynak havuzunda çalışır → health/HA sistemi node arızasını algılar → iş yükünü sağlıklı node’a yeniden başlatır/taşır → talep arttıkça node veya kaynak eklenir.'},
'15':{n:'Backup verinin geri getirilebilir kopyasını oluşturur; Disaster Recovery (DR) ise kritik hizmeti büyük kesinti veya site kaybı sonrasında yeniden çalıştırma kabiliyetidir.',o:'Ransomware, kullanıcı hatası, donanım arızası ve site felaketlerinde veri ve iş sürekliliğinin son savunma katmanıdır.',t:'Full/incremental backup, immutable/object-lock, offline/air-gap kopya, replication, local/remote DR site ve cloud backup.',c:'Veri periyodik olarak kopyalanır → en az bir kopya değiştirilemez/izole tutulur → restore testleri doğrulanır → felakette RPO/RTO hedeflerine göre DR ortamı devreye alınır.'},
'16':{n:'DCIM/BMS/EMS/NMS veri merkezi tesis ve IT telemetrisini toplar; NOC/SOC operasyon ve güvenlik olaylarını yöneten organizasyonel/teknik kontrol katmanlarıdır.',o:'Enerji, soğutma, kapasite, ağ ve güvenlik olaylarını tekil cihaz ekranlarından çıkarıp bütünsel işletme görünürlüğüne dönüştürür.',t:'DCIM, Building Management System, Energy Management System, Network Management System, NOC, SOC ve SIEM/automation entegrasyonları.',c:'Sensör ve platform verileri merkezi izleme katmanlarına akar → alarm/olay korelasyonu yapılır → operatör aksiyon alır veya kontrollü otomasyon uygulanır → KPI ve kapasite trendleri raporlanır.'},
'17':{n:'Fiziksel güvenlik tesis, oda, cage ve rack erişimini; siber güvenlik ise ağ, kimlik, sistem ve veriyi yetkisiz erişim ve saldırılardan korur.',o:'Veri merkezi güveni yalnız firewall değil, insan girişinden privileged access ve SOC olay müdahalesine kadar katmanlı kontrole dayanır.',t:'Perimeter/CCTV/mantrap/access control; IAM/MFA/PAM, segmentation, firewall, IDS/IPS, SIEM/SOC, Zero Trust ve crypto-agility.',c:'Kimlik doğrulanır → fiziksel/mantıksal erişim en az yetkiyle verilir → trafik ve olaylar sürekli izlenir → anomali tespitinde containment ve incident response süreçleri çalışır.'},
'18':{n:'AI/GPU cluster, çok sayıda accelerator/GPU sunucusunun yüksek hızlı fabric, yüksek performanslı storage ve yoğun güç/soğutma altyapısıyla tek hesaplama kümesi olarak çalışmasıdır.',o:'AI training ve büyük inference iş yükleri klasik enterprise rack yoğunluğunun çok üzerine çıkarak elektrik, cooling ve fiber tasarımını birlikte değiştirir.',t:'GPU compute node, 800G-class fabric, parallel storage, orchestration/scheduler, direct-to-chip/CDU ve yüksek yoğunluklu power zone.',c:'Veri yüksek hızlı storage’dan GPU node’larına taşınır → GPU’lar fabric üzerinden paralel hesaplama yapar → scheduler kaynakları paylaştırır → sıvı soğutma ve güç telemetrisi yoğunluğu kontrol eder.'},
'19':{n:'Sürdürülebilir veri merkezi; enerji, su, karbon, malzeme ve yaşam döngüsü etkilerini ölçerek hizmet kapasitesini daha düşük çevresel etkiyle üretmeyi hedefler.',o:'Enerji maliyeti, regülasyon, müşteri ESG beklentisi, su riski ve uzun vadeli işletme verimliliği yatırım kararını etkiler.',t:'PUE, WUE, CUE/karbon görünürlüğü, REF/yenilenebilir enerji, heat reuse, free cooling ve enerji yönetimi.',c:'Enerji/su/karbon ölçülür → kayıp ve verimsizlik kaynakları belirlenir → cooling/power/IT optimizasyonu uygulanır → yenilenebilir enerji ve ısı geri kullanım seçenekleri ekonomik olarak değerlendirilir.'},
'20':{n:'Edge veri merkezi, compute/storage/network kapasitesini merkezi tesisten kullanıcı, cihaz veya veri kaynağına daha yakın dağıtan küçük/orta ölçekli altyapıdır.',o:'Düşük gecikme, veri yerelliği, bant genişliği tasarrufu ve bağlantı kesintisinde yerel çalışmanın gerekli olduğu kullanım senaryolarına hizmet eder.',t:'Regional edge, metro edge, telco edge, industrial/OT edge ve micro data center.',c:'Gecikmeye duyarlı veri yerelde işlenir → gerekli sonuç/veri merkezi cloud’a senkronize edilir → merkezi yönetim dağıtık edge düğümlerinin güvenlik, sürüm ve kapasitesini kontrol eder.'},
'21':{n:'Kuantum bilgisayar belirli problem sınıflarında qubit tabanlı hesaplama kullanır; post-quantum cryptography (PQC) ise kuantum saldırılarına dayanıklı klasik kriptografi ailesidir.',o:'KAYAŞ için yakın dönem yatırım konusu kuantum donanımı değil; uzun ömürlü veri ve sistemlerde crypto-agility ve PQC geçiş hazırlığıdır.',t:'Superconducting, trapped-ion, photonic ve annealing quantum sistemleri; NIST PQC algoritmaları, hybrid migration ve key/certificate inventory.',c:'Quantum sistem qubit durumlarını kontrol ederek özel algoritmaları çalıştırır. PQC tarafında ise mevcut şifreleme envanteri çıkarılır → crypto-agile mimari kurulur → standart algoritmalar kontrollü geçişle devreye alınır.'},
'22':{n:'CAPEX yatırım harcamasını, OPEX işletme giderini, TCO ise seçilen dönem boyunca toplam ekonomik maliyeti; ticari fizibilite de gelir/EBITDA/nakit akışı tarafını analiz eder.',o:'Teknik olarak iyi bir tesis ancak güç, doluluk, fiyat, enerji maliyeti, finansman ve fazlama varsayımlarıyla ekonomik olarak sürdürülebilir hale gelir.',t:'CAPEX, fixed/variable OPEX, nominal ve discounted TCO; revenue, EBITDA, NPV, IRR, payback ve sensitivity senaryoları.',c:'Kapsam ve varsayımlar tanımlanır → CAPEX/OPEX ayrı modellenir → doluluk ve satılabilir kW gelir modeline bağlanır → iskonto ve hassasiyet analiziyle yatırım kararı test edilir.'},
'23':{n:'Yatırım yol haritası, teknik ve ticari yatırımların hangi sırayla ve hangi kanıt kapısı sağlandığında devreye alınacağını gösteren fazlama planıdır.',o:'Gelecekte gerekebilecek tüm teknolojiyi bugün satın almak yerine, omurgayı erken hazırlayıp aktif CAPEX’i talep ve kanıtla açarak sermaye riskini azaltır.',t:'Bugün yapılmalı, altyapısı bugün hazırlanmalı, müşteri talebiyle yapılmalı; 3/5/10 yıllık teknoloji ve kapasite kapıları.',c:'Power/site/fiber kanıtları kapanır → Faz-1 MEP ve ticari servisler açılır → doluluk/kontrat/enerji kapasitesi takip edilir → eşik sağlandığında sonraki blok veya yüksek yoğunluklu teknoloji devreye alınır.'}
};
const IMG={'01':'24_entrance','02':'12_expansion','03':'15_electrical','04':'15_electrical','05':'11_datahall','06':'14_battery','07':'15_electrical','08':'16_terrace','09':'13_fiber','10':'09_datahall','11':'10_datahall','12':'22_management','13':'09_datahall','14':'11_datahall','15':'22_management','16':'07_management','17':'03_security','18':'10_datahall','19':'16_terrace','20':'20_visitorroute','21':'21_management','22':'23_meeting','23':'24_entrance'};
const FLOW={
'01':[['Power Ready','Enerji erişimi'],['Commissioned MW','Test edilmiş kapasite'],['Sellable MW','Satılabilir ürün'],['Contracted MW','Müşteri sözleşmesi']],
'02':[['Factory / Site','Üretim'],['Module','Tekrarlanabilir blok'],['Interface','Power + cooling + fiber'],['Expansion','Talep ile büyüme']],
'03':[['Utility / OG','Şebeke'],['Transformer / Switchgear','Dönüşüm + koruma'],['UPS / Generator','Süreklilik'],['A/B Rack Power','Kritik yük']],
'04':[['Şebeke AC','50 Hz nominal'],['Rectifier','AC → DC'],['Battery / DC Link','Ride-through'],['Inverter','DC → kararlı AC'],['IT Load','Kritik yük']],
'05':[['UPS Output','A/B kaynak'],['PDU / Busway','Dağıtım'],['Tap-off','Rack hattı'],['Rack PDU','Ölçüm + besleme']],
'06':[['Grid / Renewables','Enerji girişi'],['UPS Battery / BESS','Depolama'],['BMS / EMS','Kontrol'],['Load / Grid','Çıkış']],
'07':[['Grid Loss','Kesinti'],['UPS Ride-through','İlk saniyeler'],['Generator Start','Start + sync'],['ATS / Switchgear','Yük devri'],['Continuous Run','Yakıt + bakım']],
'08':[['IT Heat','Rack ısısı'],['Air / Cold Plate','Isıyı toplama'],['CDU / HX','Devre ayrımı'],['Chiller / Dry Cooler','Heat rejection'],['8°C Water Option','Plate HX ile ayrık']],
'09':[['Carrier A/B','Fiziksel route'],['MMR / ODF','Demarkasyon'],['Spine','Fabric core'],['Leaf','Rack access'],['Compute / Storage','East-west traffic']],
'10':[['Physical Resources','Compute + storage + network'],['Virtualization','Resource pool'],['Cloud Orchestration','Policy + workflow'],['Catalog / API','Self-service'],['Metering / SLA','Ürünleşme']],
'11':[['Rack / Cage','Alan'],['Power','Contracted kW'],['Cooling','Thermal envelope'],['Connectivity','Cross-connect'],['SLA + Ops','Güven ürünü']],
'12':[['Requirement','Tier / standard hedefi'],['Design','Topoloji'],['FAT / SAT','Bileşen + saha'],['IST','Entegre test'],['ORR','Operasyon kabulü']],
'13':[['HCI Node','CPU + RAM + disk'],['Cluster','Dağıtık kaynak'],['Replication','Veri koruma'],['Federation','Merkezi yönetim']],
'14':[['Physical Hosts','Kaynak'],['Hypervisor','Soyutlama'],['HA Cluster','Health + quorum'],['Failover','İş yükü devamı'],['Scale-out','Yeni node']],
'15':[['Production','Uygulama verisi'],['Primary Backup','Hızlı restore'],['Immutable Copy','Ayrı güven sınırı'],['DR Site','Recovery compute'],['Restore Test','Kanıt']],
'16':[['Sensors / Devices','Telemetry'],['BMS / EMS / NMS','Domain systems'],['DCIM','Asset + capacity'],['NOC','Service operations'],['SOC','Threat + evidence']],
'17':[['Perimeter','Fiziksel sınır'],['Identity / MFA','Kimlik'],['Segmentation','Ağ izolasyonu'],['SIEM / SOC','Tespit'],['Incident Response','Containment']],
'18':[['Dataset','Training data'],['High-speed Storage','Parallel I/O'],['GPU Nodes','Parallel compute'],['AI Fabric','East-west'],['Scheduler + Cooling','Kaynak + termal kontrol']],
'19':[['Measure','PUE / WUE / carbon'],['Identify Loss','Verimsizlik'],['Optimize','Power + cooling + IT'],['Source Energy','Renewables'],['Report','KPI + lifecycle']],
'20':[['Central DC','Core cloud'],['Regional Edge','Metro'],['Local Edge','Site / telco'],['Device / OT','Düşük gecikme']],
'21':[['Crypto Inventory','Bugünkü durum'],['Risk / Lifetime','Uzun ömürlü veri'],['PQC Standards','ML-KEM / ML-DSA'],['Crypto-agility','Kontrollü geçiş']],
'22':[['Scope','Kapsam'],['CAPEX','Yatırım'],['OPEX','İşletme'],['TCO / NPV','Ekonomi'],['Revenue / EBITDA','Ticari fizibilite']],
'23':[['Evidence Gates','Power + site + fiber'],['Phase 1','Omurga'],['Occupancy / Contracts','Talep kanıtı'],['Next Phase','Eşik ile CAPEX']]
};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function table(rows){if(!rows||!rows.length)return'';return'<div class="table-wrap"><table>'+rows.map((r,i)=>'<tr>'+r.map(c=>(i===0?'<th>':'<td>')+esc(c)+(i===0?'</th>':'</td>')).join('')+'</tr>').join('')+'</table></div>';}
function blocks(list){let h='',open=false;for(const b of list||[]){if(b.type==='li'){if(!open){h+='<ul>';open=true}h+='<li>'+esc(b.text)+'</li>';continue}if(open){h+='</ul>';open=false}if(b.type==='h2')h+='<h3>'+esc(b.text)+'</h3>';else if(b.type==='caption')h+='<p class="caption">'+esc(b.text)+'</p>';else if(b.type==='table')h+=table(b.rows);else h+='<p>'+esc(b.text||'')+'</p>';}if(open)h+='</ul>';return h;}
function primer(id){const p=P[id];if(!p)return'';return'<div class="intro-grid"><article class="intro-card"><b>Nedir?</b><p>'+esc(p.n)+'</p></article><article class="intro-card"><b>Veri merkezindeki önemi</b><p>'+esc(p.o)+'</p></article><article class="intro-card"><b>Başlıca türleri / bileşenleri</b><p>'+esc(p.t)+'</p></article><article class="intro-card"><b>Basit çalışma mantığı</b><p>'+esc(p.c)+'</p></article></div>';}
function flow(nodes){return'<div class="flow" style="--cols:'+Math.min(nodes.length,5)+'">'+nodes.map(n=>'<div class="node"><strong>'+esc(n[0])+'</strong><span>'+esc(n[1])+'</span></div>').join('')+'</div>';}
function special(id){
 if(id==='04')return flow(FLOW[id])+'<div class="note"><strong>50 Hz:</strong> Türkiye’de nominal şebeke frekansı 50 Hz’dir; bir AC çevrimi yaklaşık 20 ms sürer. Online UPS’in inverteri kritik yüke kontrollü yeni bir AC dalga üretir.</div>';
 if(id==='13')return'<div class="special"><div class="special-panel"><h4>Geleneksel 3-tier</h4><div class="stack"><div class="layer">NETWORK</div><div class="layer">SERVER / HYPERVISOR</div><div class="layer">SAN SWITCH + STORAGE</div><div class="layer">Ayrı yönetim araçları</div></div></div><div class="vs">→</div><div class="special-panel"><h4>HCI cluster</h4><div class="hci-nodes"><div class="hci-node"><b>NODE 1</b>CPU/RAM<br>Local disks<br>Hypervisor<br>HCI SW</div><div class="hci-node"><b>NODE 2</b>CPU/RAM<br>Local disks<br>Hypervisor<br>HCI SW</div><div class="hci-node"><b>NODE 3</b>CPU/RAM<br>Local disks<br>Hypervisor<br>HCI SW</div></div><div class="note">Yeni node, cluster compute/storage kapasitesini scale-out mantığıyla büyütebilir; federation ve site replikasyonu platforma göre entegre edilir.</div></div></div>';
 if(id==='18')return'<div class="special"><div class="special-panel"><h4>CPU — az sayıda güçlü çekirdek</h4><div class="cores"><div class="core cpu"></div><div class="core cpu"></div><div class="core cpu"></div><div class="core cpu"></div></div><p class="note">Genel amaç, OS, DB, control-flow ve düşük gecikmeli işler.</p></div><div class="vs">VS</div><div class="special-panel"><h4>GPU — yüksek paralellik</h4><div class="cores">'+Array.from({length:24}).map(()=>'<div class="core"></div>').join('')+'</div><p class="note">Tensor/matris işlemleri, AI training/inference, rendering ve HPC.</p></div></div>';
 if(id==='21')return'<div class="special"><div class="special-panel bitbox"><h4>Klasik bit</h4><div class="bits"><span class="bit">0</span><span class="bit">1</span></div><p class="note">Temel mantıksal durum ölçümde 0 veya 1’dir.</p></div><div class="vs">VS</div><div class="special-panel bitbox"><h4>Qubit</h4><div class="qubit"><i></i></div><p class="note">|ψ⟩ = α|0⟩ + β|1⟩. Ölçüm yine 0 veya 1 verir; ölçüm öncesi durum süperpozisyon genlikleriyle tanımlanır. Interference ve entanglement bazı algoritmalara farklı hesaplama yapısı sağlar.</p></div></div>';
 return flow(FLOW[id]||[]);
}
function imagePath(id){const x=IMG[id]||'09_datahall';return'../assets/gallery/kayas_concept_'+x+'.webp';}
function visual(id,title){return'<div class="visual"><div class="visual-grid"><div class="visual-media"><img loading="lazy" decoding="async" src="'+imagePath(id)+'" alt="'+esc(title)+' için KAYAŞ konsept görseli"></div><div class="diagram"><div class="eyebrow">BASİT ÇALIŞMA MANTIĞI</div><h3>'+esc(title)+'</h3>'+special(id)+'<div class="note">Konsept anlatım; nihai mühendislik çizimi, SLD/P&amp;ID veya üretici performans garantisi değildir.</div></div></div></div>';}
function chapterSection(c){const id='chapter-'+c.id;return'<section class="paper" id="'+id+'"><div class="section-head"><div class="section-no">'+esc(c.id)+'</div><div><div class="eyebrow">KONUYA HIZLI GİRİŞ + DETAYLI İNCELEME</div><h1>'+esc(c.title)+'</h1></div></div>'+primer(c.id)+visual(c.id,c.title)+'<div class="chapter-body">'+blocks(c.blocks)+'</div><div style="display:flex;justify-content:space-between;gap:10px;margin-top:28px;padding-top:16px;border-top:1px solid var(--line)"><a href="#toc">← İndekse dön</a><a href="#top">Başa dön ↑</a></div></section>';}
function appendixSection(c){return'<section class="paper" id="appendix-'+esc(c.id)+'"><div class="section-head"><div class="section-no">'+esc(c.id.replace('EK-','EK '))+'</div><div><div class="eyebrow">EK / REFERANS</div><h1>'+esc(c.title)+'</h1></div></div><div class="chapter-body">'+blocks(c.blocks)+'</div><div style="display:flex;justify-content:space-between;gap:10px;margin-top:28px;padding-top:16px;border-top:1px solid var(--line)"><a href="#toc">← İndekse dön</a><a href="#top">Başa dön ↑</a></div></section>';}
const chapters=guide.chapters.filter(c=>c.kind!=='appendix'&&/^\d+$/.test(c.id));const appendices=guide.chapters.filter(c=>c.kind==='appendix'||!/^\d+$/.test(c.id));
document.getElementById('chapters').innerHTML=chapters.map(chapterSection).join('');document.getElementById('appendices').innerHTML=appendices.map(appendixSection).join('');
function buildToc(q=''){const n=q.toLocaleLowerCase('tr-TR');const filtered=chapters.filter(c=>(c.id+' '+c.title+' '+c.blocks.map(b=>b.text||'').join(' ')).toLocaleLowerCase('tr-TR').includes(n));document.getElementById('tocGrid').innerHTML=filtered.map(c=>'<a class="toc-link" href="#chapter-'+esc(c.id)+'"><b>'+esc(c.id)+'</b><span>'+esc(c.title)+'</span></a>').join('')||'<p>Arama kriterine uygun bölüm bulunamadı.</p>';document.getElementById('appendixToc').innerHTML=appendices.length?'<div class="appendix-title">EKLER</div><div class="toc-grid">'+appendices.map(c=>'<a class="toc-link" href="#appendix-'+esc(c.id)+'"><b>'+esc(c.id.replace('EK-','EK '))+'</b><span>'+esc(c.title)+'</span></a>').join('')+'</div>':'';}
buildToc();document.getElementById('tocSearch').addEventListener('input',e=>buildToc(e.target.value.trim()));
const menu=document.getElementById('menuToggle'),nav=document.getElementById('topNav');menu.addEventListener('click',()=>{const o=nav.classList.toggle('is-open');menu.setAttribute('aria-expanded',String(o));});nav.querySelectorAll('a,button').forEach(x=>x.addEventListener('click',()=>{nav.classList.remove('is-open');menu.setAttribute('aria-expanded','false');}));document.getElementById('printButton').addEventListener('click',()=>window.print());document.addEventListener('click',e=>{if(innerWidth<=900&&!nav.contains(e.target)&&e.target!==menu){nav.classList.remove('is-open');menu.setAttribute('aria-expanded','false');}});
})();