(()=>{
'use strict';
if(window.SPECBRIDGE_KAYAS_MOBILE)return;window.SPECBRIDGE_KAYAS_MOBILE=true;
const mq=matchMedia('(max-width:820px)');
let mode=null;
function mobile(){return mq.matches}
function clone(sel){const src=document.querySelector(sel);if(!src)return '<div class="smallnote">No content is available for this view.</div>';const c=src.cloneNode(true);c.removeAttribute('id');c.querySelectorAll('[id]').forEach(x=>x.removeAttribute('id'));return c.outerHTML}
function sourceFor(kind){const master=document.body.classList.contains('kx-master-open');if(kind==='why')return master?'.kx-m-left':'.left';if(kind==='details')return master?'.kx-m-right':'.right';return null}
function controlsHtml(){const keys=[['flow','Flow'],['design','Design Paths'],['labels','Labels'],['evidence','Evidence']];return `<div class="sbm-controls">${keys.map(([k,n])=>{const b=document.querySelector(`.kx-semantic button[data-k="${k}"]`);return `<button data-proxy="${k}" class="${b?.classList.contains('on')?'on':''}">${n}: ${b?.classList.contains('on')?'On':'Off'}</button>`}).join('')}<button data-action="fit">Fit Topology</button><button data-action="master">K00 Master</button></div>`}
function render(kind){const body=document.querySelector('#sbmSheet .sbm-body'),title=document.querySelector('#sbmSheet .sbm-head b'),sub=document.querySelector('#sbmSheet .sbm-head span');if(!body)return;mode=kind;document.querySelectorAll('#sbmDock button').forEach(b=>b.classList.toggle('active',b.dataset.kind===kind));if(kind==='controls'){title.textContent='Controls';sub.textContent='Mobile architecture controls';body.innerHTML=controlsHtml();body.querySelectorAll('[data-proxy]').forEach(b=>b.onclick=()=>{const p=document.querySelector(`.kx-semantic button[data-k="${b.dataset.proxy}"]`);p?.click();render('controls')});body.querySelector('[data-action="fit"]')?.addEventListener('click',fit);body.querySelector('[data-action="master"]')?.addEventListener('click',()=>{close();window.KAYAS_K00_OPEN?.()});return}const sel=sourceFor(kind);title.textContent=kind==='why'?'Why / Narrative':'Details / Evidence';sub.textContent=kind==='why'?'Design context':'Selected infrastructure object';body.innerHTML=clone(sel);body.querySelectorAll('a').forEach(a=>{a.target=a.target||'_blank';a.rel='noopener'});}
function open(kind){if(!mobile())return;render(kind);document.body.classList.add('sbm-sheet-open')}
function close(){document.body.classList.remove('sbm-sheet-open');document.querySelectorAll('#sbmDock button').forEach(b=>b.classList.remove('active'));mode=null}
function fit(){close();const active=document.querySelector('.tab.active,#tabs button.active');if(active){active.click();return}window.dispatchEvent(new Event('resize'))}
function install(){if(document.getElementById('sbmDock'))return;const back=document.createElement('div');back.id='sbmBackdrop';back.onclick=close;const sheet=document.createElement('section');sheet.id='sbmSheet';sheet.setAttribute('aria-label','Mobile architecture panel');sheet.innerHTML='<div class="sbm-head"><div><b>Details</b><span></span></div><button type="button" aria-label="Close">×</button></div><div class="sbm-body"></div>';sheet.querySelector('.sbm-head button').onclick=close;const dock=document.createElement('nav');dock.id='sbmDock';dock.setAttribute('aria-label','Mobile architecture navigation');dock.innerHTML='<button data-kind="why">Why</button><button data-kind="details">Details</button><button data-kind="controls">Controls</button><button data-kind="fit">Fit</button>';dock.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;b.dataset.kind==='fit'?fit():open(b.dataset.kind)});const hint=document.createElement('div');hint.id='sbmRotateHint';hint.textContent='Rotate to landscape for maximum topology space';document.body.append(back,sheet,dock,hint);
 document.addEventListener('click',e=>{if(!mobile())return;if(e.target.closest('.nodecard,.kx-map-card'))setTimeout(()=>open('details'),80)},true);
 const right=document.querySelector('.right');if(right)new MutationObserver(()=>{if(mobile()&&mode==='details')render('details')}).observe(right,{subtree:true,childList:true,characterData:true});
 mq.addEventListener?.('change',()=>{if(!mobile())close()});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
