(function(){
  'use strict';
  const guide=window.KAYAS_GUIDE;
  if(!guide)return;

  const G={
    entrance:['../assets/gallery/kayas_concept_01_entrance.webp','Batı giriş / mevcut erişim'],reception:['../assets/gallery/kayas_concept_02_reception.webp','Resepsiyon ve güvenlik masası'],security:['../assets/gallery/kayas_concept_03_security.webp','Kontrollü geçiş / mantrap'],foyer:['../assets/gallery/kayas_concept_04_foyer.webp','Foyer ve gelecek genişleme showroomu'],meeting:['../assets/gallery/kayas_concept_05_meeting.webp','Yatırımcı bilgilendirme alanı'],operator:['../assets/gallery/kayas_concept_06_operator.webp','Operatör odaları'],noc:['../assets/gallery/kayas_concept_07_management.webp','NOC yönetim merkezi'],carrier:['../assets/gallery/kayas_concept_08_carrier.webp','Carrier meet-me room'],hall:['../assets/gallery/kayas_concept_09_datahall.webp','Ana IC8000 veri salonu'],aisle:['../assets/gallery/kayas_concept_10_datahall.webp','IC8000 soğuk koridor'],service:['../assets/gallery/kayas_concept_11_datahall.webp','Arka servis koridoru'],expansion:['../assets/gallery/kayas_concept_12_expansion.webp','Kuzey gelecek genişleme alanı'],fiber:['../assets/gallery/kayas_concept_13_fiber.webp','Güney fiber odası'],battery:['../assets/gallery/kayas_concept_14_battery.webp','Akü odası ve havalandırma'],electrical:['../assets/gallery/kayas_concept_15_electrical.webp','Elektrik dağıtım ve bypass alanı'],cooling:['../assets/gallery/kayas_concept_16_terrace.webp','Doğu teras soğutma tesisi'],coolingWalk:['../assets/gallery/kayas_concept_17_terrace.webp','Mekanik bakım geçişi'],terrace:['../assets/gallery/kayas_concept_18_terrace.webp','Ayrılmış açık teras'],route:['../assets/gallery/kayas_concept_20_visitorroute.webp','Ziyaretçi gözlem rotası'],executive:['../assets/gallery/kayas_concept_21_management.webp','Yönetici ofisi'],nocAlt:['../assets/gallery/kayas_concept_22_management.webp','NOC operasyon merkezi'],board:['../assets/gallery/kayas_concept_23_meeting.webp','Yönetim kurulu / yatırımcı toplantı odası'],exterior:['../assets/gallery/kayas_concept_24_entrance.webp','Dış cephe akşam görünümü']
  };

  const P={
    '00':{eyebrow:'REHBER KULLANIMI',status:'EXECUTIVE READING MODE',kpis:[['23','Ana bölüm'],['6','Ek'],['6','Bilgi statüsü'],['1','Karar yüzeyi']],insight:['Önce yönetici özeti ve kanıt kapıları okunmalı.','Her sayısal değer bilgi statüsü ile değerlendirilmelidir.','Bağlayıcı yatırım kararı için ilgili kanıt / mühendislik teyidi aranmalıdır.'],graphic:{type:'steps',title:'Rehberi karar aracına çeviren okuma sırası',items:['Baseline','Karar sınıfı','Teknik kanıt','Risk / açık konu','Yatırım kararı']},imgs:['board','hall','noc','meeting'],related:['01','23','EK-A','EK-B']},
    '01':{eyebrow:'YATIRIM TEZİ',status:'BUDGETARY / VALIDATION REQUIRED',kpis:[['206','Faz-1 IT kabinet'],['1.972 MW','IT tasarım yükü'],['≈2.000','Uzun vadeli vizyon'],['Tier III','Hedef']],insight:['Yatırım birimi yalnız kabinet değil, satılabilir ve arıza sonrası ayakta kalan kW/MW olmalıdır.','İlk ticari omurga colocation + private cloud + backup/DR + managed services olarak ele alınır.','Büyüme, talep ve kanıt kapıları ile fazlanmalıdır.'],graphic:{type:'valueStack',title:'KAYAS yatırım değeri nasıl oluşur?',layers:[['Fiziksel DC','IC8000 • güç • soğutma'],['Dijital altyapı','Compute / HCI • storage • network'],['Bulut platformu','CAS • CloudOS • self-service'],['Koruma','Security • backup • DR'],['Gelir katmanı','Colocation • IaaS • managed services • AI/GPU']]},imgs:['board','meeting','hall','exterior'],related:['10','11','22','23']},
    '02':{eyebrow:'FİZİKSEL MİMARİ',status:'ARCHITECTURE CHOICE / SITE VALIDATION REQUIRED',kpis:[['3','Mimari yaklaşım'],['10','Mikro modül koridoru'],['206','IT kabinet baseline'],['≈2.000 m²','Çalışma alanı']],insight:['Mikro-modül yaklaşımı fiziksel altyapı, containment ve Day-2 operasyonu birlikte ele alır.','Prefabrik / modüler yaklaşım, büyüme fazlarında ayrı bir araçtır; her alan için otomatik olarak doğru değildir.','Son seçim saha, statik, yangın, bakım ve genişleme koşullarıyla doğrulanmalıdır.'],graphic:{type:'compare3',title:'Veri merkezi fiziksel mimari seçenekleri',cols:[['Geleneksel','Yüksek saha özelleştirmesi','Proje bazlı entegrasyon','Esnek fakat entegrasyon yükü yüksek'],['Mikro-modül','Containment + rack + power/cooling','Standartlaştırılmış modül','Faz-1 için ana çalışma yönü'],['Prefabrik modüler','Fabrika entegrasyonu','Hızlı faz ekleme','Gelecek genişleme alternatifi']]},imgs:['hall','aisle','service','expansion'],related:['03','08','12','23']},
    '03':{eyebrow:'ELEKTRİK OMURGASI',status:'H3C PROPOSAL / RECALCULATION REQUIRED',kpis:[['1.972 MW','Güncel IT yükü'],['2N','IT güç yolu hedefi'],['16.5 MW','Customer input'],['OPEN','Tesis gücü sizing']],insight:['1.972 kW IT yükü esas alınarak UPS, trafo, jeneratör, soğutma ve yardımcı yükler birlikte yeniden hesaplanmalıdır.','3.100 kW toplam tesis gücü doğrulanmadan kesin değer değildir.','16,5 MW saha kapasitesi müşteri girdisidir; resmi elektrik teyidi gerekir.'],graphic:{type:'powerDual',title:'Konsept güç zinciri — çift güç yolu hedefi',a:['Şebeke / Trafo A','Şalt A','UPS A','PDU / Busway A'],b:['Şebeke / Trafo B','Şalt B','UPS B','PDU / Busway B'],end:'IT yükü 1.972 MW'},imgs:['electrical','battery','hall','cooling'],related:['04','05','06','07']},
    '04':{eyebrow:'UPS / RIDE-THROUGH',status:'CONCEPT TARGET / FINAL SIZING REQUIRED',kpis:[['2N','IT yol hedefi'],['≈15 dk','Tam yük akü hedefi'],['8×600 kVA','IT UPS konsepti'],['2×500 kVA','Mekanik UPS konsepti']],insight:['UPS, şebeke kaybı ile jeneratör devreye girişi arasındaki süreyi köprüler; sürekli enerji kaynağı olarak boyutlandırılmaz.','Tam yükte yaklaşık 15 dakika akü hedefi konsept seviyesindedir.','Son yük, güç faktörü, verim, büyüme ve redundancy senaryosu ile sizing yenilenmelidir.'],graphic:{type:'rideThrough',title:'Kesinti anında enerji sürekliliği',items:[['0 ms','Şebeke sapması / kesinti'],['< çevrim','UPS inverter yükü taşır'],['saniyeler','Jeneratör start & stabilizasyon'],['transfer','UPS + jeneratör birlikte'],['normal','Şebeke dönüş / kontrollü retransfer']]},imgs:['battery','electrical','hall','noc'],related:['03','06','07','12']},
    '05':{eyebrow:'RACK GÜÇ DAĞITIMI',status:'DESIGN DETAIL REQUIRED',kpis:[['A/B','Rack besleme'],['7 kW','Standart rack'],['60 kW','AI/HPC rack'],['Metering','Gerekli']],insight:['PDU / busway seçimi rack yoğunluğu, A/B besleme, ölçüm ve bakım senaryosuyla birlikte yapılmalıdır.','7 kW standart rack ile 60 kW AI/HPC rack aynı dağıtım varsayımıyla ele alınmamalıdır.','Satılabilir kW ve müşteri faturalaması için ölçüm noktaları tasarım girdisidir.'],graphic:{type:'distribution',title:'Tesisten kabinete güç dağıtım hiyerarşisi',root:'UPS A/B',branches:[['Busway A','Rack PDU-A'],['Busway B','Rack PDU-B']],loads:[['Standart rack','7 kW'],['AI/HPC rack','60 kW']]},imgs:['electrical','service','aisle','hall'],related:['03','04','13','18']},
    '06':{eyebrow:'AKÜ / ENERJİ DEPOLAMA',status:'BATTERY ENGINEERING REQUIRED',kpis:[['≈15 dk','UPS autonomy target'],['2N','IT continuity intent'],['BESS','Future-ready'],['OPEN','Chemistry / room design']],insight:['Akü odası; yük, kimya, yangın, havalandırma, ağırlık ve bakım şartlarıyla birlikte tasarlanmalıdır.','UPS aküsü ile uzun süreli enerji depolama / BESS aynı fonksiyon değildir.','Üst kat yerleşimde döşeme yükü ve yangın mühendisliği kritik kanıt kapısıdır.'],graphic:{type:'batteryRoles',title:'Enerji depolamada rol ayrımı',items:[['UPS Battery','Saniye-dakika ride-through','Kritik yük sürekliliği'],['Generator','Uzun süreli standby','Yakıt + start + bakım'],['Future BESS','Enerji yönetimi / farklı kullanım','Ayrı fizibilite ve güvenlik']]},imgs:['battery','electrical','cooling','noc'],related:['03','04','07','19']},
    '07':{eyebrow:'STANDBY GÜÇ',status:'GENERATOR SIZING / FUEL STRATEGY REQUIRED',kpis:[['N+?','Yedeklilik teyidi'],['1.972 MW','IT baz yük'],['MEP','Yardımcı yük eklenmeli'],['OPEN','Yakıt / runtime']],insight:['Jeneratör kapasitesi yalnız IT MW üzerinden seçilemez; mekanik ve yardımcı kritik yükler dahil edilmelidir.','Start sırası, yük alma adımları, yakıt lojistiği ve bakım bypass senaryosu tanımlanmalıdır.','UPS ve jeneratör birlikte tek süreklilik zinciri olarak test edilmelidir.'],graphic:{type:'steps',title:'Şebeke kesintisinde standby güç sekansı',items:['Şebeke kaybı','UPS yükü taşır','Jeneratör start','Gerilim/frekans stabil','ATS/şalt transfer','Kritik yük normalleşir']},imgs:['electrical','exterior','battery','hall'],related:['03','04','06','12']},
    '08':{eyebrow:'HİBRİT SOĞUTMA',status:'OPEN-CONFIRMATION REQUIRED',kpis:[['196','Hava soğutmalı rack'],['10','Sıvı soğutmalı rack'],['600 kW','Liquid zone'],['≈8°C','Doğal su input']],insight:['Doğal su IT devresine doğrudan bağlanmamalı; ısı eşanjörü / CDU ile hidrolik olarak ayrılmalıdır.','CDU adet, kapasite, konum ve yedekliliği henüz kesinleşmemiştir.','8°C kaynak fırsattır; debi, mevsimsellik, kimya, izin ve backup mekanik kapasite doğrulanmalıdır.'],graphic:{type:'coolingDual',title:'Hava + sıvı soğutma birlikte nasıl çalışır?',air:['196 rack × 7 kW','Containment / in-row','DX veya chilled-water tarafı'],liquid:['10 rack × 60 kW','CDU / kapalı IT loop','600 kW tasarım yükü'],source:['≈8°C doğal su','Plakalı eşanjör','Yedek mekanik soğutma']},imgs:['cooling','coolingWalk','aisle','hall'],related:['03','18','19','23']},
    '09':{eyebrow:'FIBER / DC NETWORK',status:'PHYSICAL DIVERSITY PROOF REQUIRED',kpis:[['MMR-A/B','Hedef'],['2','Bağımsız fiber giriş'],['EVPN/VXLAN','DC fabric'],['OOB','Ayrı yönetim']],insight:['Carrier-neutral iddiası fiziksel olarak bağımsız iki güzergâh ve MMR kanıtına dayanmalıdır.','Spine-leaf / EVPN-VXLAN mantıksal fabric, fiziksel fiber çeşitliliğinin yerine geçmez.','OOB yönetim ağı üretim fabric’inden ayrılmalıdır.'],graphic:{type:'network',title:'Fiziksel çeşitlilik + mantıksal fabric',left:['Carrier A','MMR-A'],right:['Carrier B','MMR-B'],core:['Spine-1','Spine-2'],leaf:['Leaf pair','Leaf pair'],end:'Compute • Storage • Cloud • OOB ayrı'},imgs:['fiber','carrier','nocAlt','hall'],related:['10','15','17','20']},
    '10':{eyebrow:'CLOUD HİZMETLERİ',status:'SERVICE ARCHITECTURE / COMMERCIAL VALIDATION',kpis:[['CloudOS','Cloud management'],['VDC','Multi-tenant'],['Catalog','Self-service'],['Metering','Chargeback-ready']],insight:['Cloud hizmeti yalnız sanallaştırma değildir; tenant, katalog, quota, workflow ve ölçüm birlikte ürünleştirilmelidir.','İlk servis omurgası private-cloud IaaS ile başlatılıp operasyon olgunluğuna göre genişletilmelidir.','Exact edition, lisans, HCL ve destek kapsamı yazılı teyit edilmelidir.'],graphic:{type:'cloudStack',title:'Müşteri talebinden ölçülebilir cloud servisine',top:['Tenant / Müşteri','Portal / Self-service'],mid:['Catalog','Quota / Workflow','VDC'],platform:['CloudOS','CAS','ONEStor'],infra:['UIS / Compute','Network','Security'],bottom:'Metering • SLA • Billing input'},imgs:['nocAlt','noc','board','hall'],related:['11','13','14','15']},
    '11':{eyebrow:'COLOCATION',status:'COMMERCIAL PRODUCT DESIGN REQUIRED',kpis:[['Rack/kW','Ana ürün'],['Cross-connect','Ek gelir'],['Transit','Connectivity'],['SLA','Yazılı ürün']],insight:['Colocation satış birimi rack sayısından çok satılabilir kW, güç yolu, bağlantı ve SLA kombinasyonudur.','Cross-connect ve internet transit, çekirdek colocation gelirini tamamlayan servislerdir.','Doluluk, güç rezervi ve kontratlı kapasite ayrı izlenmelidir.'],graphic:{type:'coloStack',title:'Colocation ürününün gelir katmanları',items:[['Space','Rack / cage / zone'],['Power','Committed & metered kW'],['Connectivity','Cross-connect / carrier / transit'],['Operations','Remote hands / NOC'],['SLA','Availability + support scope']]},imgs:['hall','aisle','carrier','meeting'],related:['01','09','10','22']},
    '12':{eyebrow:'TIER / COMMISSIONING',status:'TIER III TARGET — NOT CERTIFIED',kpis:[['Tier III','Hedef'],['FAT','Factory'],['SAT','Site'],['IST','Integrated']],insight:['Tier III ifadesi hedefi belirtir; sertifika veya constructed-facility kanıtı değildir.','Commissioning ürün testi değil, sistemlerin birlikte ve arıza senaryolarında doğrulanmasıdır.','FAT → SAT → IST → operational readiness zinciri yatırım kabul planına bağlanmalıdır.'],graphic:{type:'gates',title:'Tasarım hedefinden işletilebilir tesise kanıt zinciri',items:[['Design Review','Kapsam / redundancy'],['FAT','Ürün ve paket'],['SAT','Sahada kurulum'],['IST','Entegre arıza senaryoları'],['ORR / Handover','İşletme hazırlığı']]},imgs:['electrical','cooling','route','nocAlt'],related:['03','08','16','23']},
    '13':{eyebrow:'COMPUTE / STORAGE / HCI',status:'WORKING BOM / SIZING CONFIRMATION REQUIRED',kpis:[['19×','UIS 3000 G6'],['4×','R4900 G6'],['CAS','Virtualization'],['ONEStor','Storage']],insight:['19× UIS 3000 G6 + 4× R4900 G6 çalışma BOM baseline’ıdır; final sizing değildir.','CAS, ONEStor ve UIS yönetim katmanı tek platform mimarisi içinde değerlendirilmelidir.','Eski 12/15 node senaryoları güncel baseline ile karıştırılmamalıdır.'],graphic:{type:'hci',title:'HCI altyapıdan cloud servisine katmanlar',nodes:[['19× UIS 3000 G6','HCI resource pool'],['4× R4900 G6','Dedicated / auxiliary compute']],layers:['CAS Virtualization','ONEStor Distributed Storage','UIS Manager','CloudOS Integration']},imgs:['hall','aisle','service','nocAlt'],related:['10','14','15','18']},
    '14':{eyebrow:'SANALLAŞTIRMA / BÜYÜME',status:'FAILURE-DOMAIN DESIGN REQUIRED',kpis:[['HA','Node failure'],['AZ','Domain separation'],['DR','Separate site'],['Scale-out','Demand-led']],insight:['HA, availability zone ve coğrafi DR aynı şey değildir; her biri farklı failure domain’i hedefler.','Aynı kampüsteki AZ, coğrafi DR olarak pazarlanmamalıdır.','Büyüme node sayısından önce compute, storage, network ve lisans darboğazlarıyla birlikte modellenmelidir.'],graphic:{type:'failureDomains',title:'Yedeklilik katmanlarını doğru ayırmak',items:[['Node HA','Tek sunucu / bileşen arızası'],['Rack / Pod','Yerel güç-ağ failure domain'],['AZ / Hall','Ayrılmış salon / altyapı domaini'],['DR Site','Coğrafi / bağımsız saha']],arrow:'Kapsam büyüdükçe bağımsızlık gereksinimi artar'},imgs:['hall','nocAlt','expansion','service'],related:['10','13','15','23']},
    '15':{eyebrow:'BACKUP / DR',status:'RECOVERY TEST REQUIRED',kpis:[['Backup','Copy'],['Replication','Secondary'],['Restore','Test'],['DRaaS','Service']],insight:['Backup başarı metriği yalnız kopya oluşması değil, restore edilebilirliktir.','RPO / RTO müşteri servis sınıfına göre tanımlanmalı ve test sonuçlarıyla doğrulanmalıdır.','DRaaS için hedef site bağımsızlığı, network, runbook ve düzenli tatbikat gerekir.'],graphic:{type:'recovery',title:'Veriden iş sürekliliğine recovery zinciri',items:[['Production','Primary workload'],['Backup','Protected copy'],['Replica / DR','Independent recovery target'],['Restore Test','Evidence'],['DR Runbook','Operational service']]},imgs:['fiber','nocAlt','electrical','expansion'],related:['09','10','14','16']},
    '16':{eyebrow:'DCIM / NOC / SOC',status:'DAY-2 OPERATING MODEL',kpis:[['DCIM','Facility'],['BMS/EMS','MEP'],['NMS','Network'],['NOC/SOC','Operations']],insight:['Araç sayısından çok alarmın aksiyona dönüşme zinciri önemlidir.','DCIM/BMS/EMS/NMS verileri korelasyon, ticket, SLA ve eskalasyon modeline bağlanmalıdır.','7/24 NOC ve named L2/L3 destek kapsamı yazılı operasyon modeli gerektirir.'],graphic:{type:'ops',title:'Telemetry → karar → müdahale',sources:['Power / UPS','Cooling / CDU','Rack sensors','Network','Security'],platform:['DCIM / BMS / EMS','NMS / Analyzer','SOC tooling'],ops:['NOC / SOC','Ticket + SLA','L2/L3 escalation']},imgs:['noc','nocAlt','operator','executive'],related:['12','15','17','23']},
    '17':{eyebrow:'FİZİKSEL + SİBER GÜVENLİK',status:'SECURITY ARCHITECTURE',kpis:[['Perimeter','Physical'],['DDoS/FW','North-South'],['Segmentation','East-West'],['SOC','Response']],insight:['Fiziksel erişim, perimeter güvenliği ve east-west segmentasyon tek güvenlik modeli içinde ele alınmalıdır.','DDoS, firewall, ADC, VPN/MPLS ve segmentasyon servis kapsamına göre tasarlanmalıdır.','Kontrol varlığı kadar log, korelasyon, olay müdahalesi ve SLA önemlidir.'],graphic:{type:'securityRings',title:'Defense-in-depth — tesisten workload’a',rings:['Site / Access','Perimeter / DDoS','Firewall / ADC','Segmentation','Workload / Identity','SOC / Incident Response']},imgs:['security','route','nocAlt','carrier'],related:['09','10','15','16']},
    '18':{eyebrow:'AI / GPU CLUSTER',status:'FUTURE-READY / DEMAND-LED',kpis:[['10','Liquid racks'],['60 kW','Rack design'],['600 kW','AI/HPC zone'],['CDU','Required']],insight:['AI/GPU alanı standart 7 kW rack tasarımından ayrı güç, network ve soğutma failure domain’i olarak ele alınmalıdır.','10×60 kW = 600 kW tasarım yükü mevcut çalışma baseline’ıdır.','İlave GPU kapasitesi müşteri talebiyle ve enerji/soğutma kanıtıyla açılmalıdır.'],graphic:{type:'aiPod',title:'AI cluster için birlikte büyümesi gereken 4 katman',items:[['GPU Compute','High-density nodes'],['Network Fabric','Low-latency east-west'],['Rack Power','60 kW/rack design'],['Liquid Cooling','CDU + closed loop']],footer:'10 rack × 60 kW = 600 kW mevcut AI/HPC tasarım zonu'},imgs:['hall','aisle','cooling','coolingWalk'],related:['08','09','13','19']},
    '19':{eyebrow:'SÜRDÜRÜLEBİLİRLİK',status:'MEASURE BEFORE CLAIM',kpis:[['PUE','Ölç'],['WUE','Ölç'],['≈8°C','Fırsat'],['Metering','Şart']],insight:['PUE/WUE hedefleri ölçüm mimarisi ve gerçek işletme verisi olmadan iddia edilmemelidir.','≈8°C doğal kaynak free-cooling fırsatı yaratabilir ancak kaynak testi ve yedek mekanik kapasite şarttır.','Enerji verimliliği, su kullanımı ve karbon etkisi ayrı KPI’larla takip edilmelidir.'],graphic:{type:'sustain',title:'Sürdürülebilirlik iddiası için ölçüm zinciri',items:[['Measure','IT kWh • facility kWh • water'],['Baseline','PUE • WUE • load profile'],['Optimize','Cooling • power • utilization'],['Verify','Seasonal data • alarms • tests'],['Report','Customer / management KPI']]},imgs:['cooling','coolingWalk','terrace','expansion'],related:['06','08','18','22']},
    '20':{eyebrow:'EDGE VERİ MERKEZLERİ',status:'FUTURE SERVICE OPTION',kpis:[['Core','KAYAS'],['Edge','Demand-led'],['Fiber','Prerequisite'],['Ops','Centralized']],insight:['Edge, ana KAYAS tesisinin yerine geçen değil; gecikme, veri yerelliği veya saha gereksinimi olduğunda tamamlayan bir modeldir.','Edge node’lar merkezi cloud, network, security ve operasyon standartlarına bağlanmalıdır.','Yatırım müşteri / kullanım senaryosu kanıtıyla açılmalıdır.'],graphic:{type:'edge',title:'Merkezden edge düğümlerine servis modeli',hub:'KAYAS Core DC',spokes:[['Edge A','Low-latency'],['Edge B','Local processing'],['Edge C','Customer/site node']],links:'Fiber / SD-WAN / secure connectivity'},imgs:['carrier','fiber','noc','exterior'],related:['09','10','16','21']},
    '21':{eyebrow:'QUANTUM / PQC',status:'PREPARE INTERFACES — DO NOT OVERBUILD',kpis:[['PQC','Hazırlık'],['Crypto inventory','Gerekli'],['Quantum HW','Talep ile'],['Roadmap','Lifecycle']],insight:['Bugün için ana yatırım konusu on-prem quantum donanımı değil, kriptografik çevikliğe ve PQC geçişine hazırlıktır.','Crypto inventory, lifecycle ve vendor roadmap izlenmelidir.','Quantum donanım yatırımı müşteri talebi ve iş modeli olmadan erken CAPEX olur.'],graphic:{type:'nowPrepareDemand',title:'Quantum/PQC yatırım zamanlaması',now:['Crypto inventory','Lifecycle / algorithm dependency'],prepare:['PQC-ready architecture','Key / certificate agility'],demand:['On-prem quantum hardware','Specialized services']},imgs:['noc','board','fiber','hall'],related:['17','20','22','23']},
    '22':{eyebrow:'CAPEX / OPEX / TCO',status:'BUDGETARY / COMMERCIAL VALIDATION REQUIRED',kpis:[['CAPEX','Build'],['OPEX','Operate'],['TCO','Lifecycle'],['Sellable kW','Decision unit']],insight:['Kabinet fiyatı toplam veri merkezi yatırımını temsil etmez; MEP, entegrasyon, lisans, lojistik, devreye alma ve servis dahil edilmelidir.','TCO; CAPEX + OPEX + lifecycle + lisans + support + enerji etkisini birlikte ele almalıdır.','Bir sonraki faz kararı kontratlı/satılabilir kW, doluluk, fiyat ve tahsilat varsayımlarıyla verilmelidir.'],graphic:{type:'finance',title:'Teklif fiyatından gerçek TCO’ya',items:[['Equipment','Rack • IT • network'],['MEP','Power • cooling • fire'],['Delivery','Logistics • install • Cx'],['Software','License • subscription'],['Operations','Energy • staff • support'],['Lifecycle','Refresh • spares • expansion']]},imgs:['board','meeting','executive','exterior'],related:['01','11','19','23']},
    '23':{eyebrow:'YATIRIM YOL HARİTASI',status:'PROGRAM CONTROL / DATES SUBJECT TO DEPENDENCIES',kpis:[['17 Ağu 2026','IC8000 PO hedefi'],['Ağu 2026','Ticari kapanış'],['Şub 2027','Açılış hedefi'],['OPEN','Critical path']],insight:['Tarihler SPQ, sözleşme, üretim, ithalat, saha hazırlığı ve mühendislik onaylarına tabidir.','Kritik yol; güç, soğutma, statik/yangın, fiber ve commissioning kanıt kapılarıyla birlikte yönetilmelidir.','Eski baseline sessizce silinmemeli; revizyon kaydı tutulmalıdır.'],graphic:{type:'roadmap',title:'KAYAS Faz-1 yönetici yol haritası',items:[['17 Ağu 2026','IC8000 ticari onay / PO'],['Ağu 2026','Ticari kapanış'],['Engineering Freeze','MEP + BoQ + site evidence'],['FAT / Logistics','Üretim + ithalat'],['SAT / IST','Saha + entegre test'],['Şub 2027','Hedef açılış']]},imgs:['expansion','electrical','cooling','fiber'],related:['03','08','12','22']},
    'EK-A':{eyebrow:'KARAR MATRİSİ',status:'PROGRAM CONTROL',kpis:[['Bugün','Yapılmalı'],['Hazırla','Future-ready'],['Talep','Demand-led'],['Gate','Evidence']],insight:['Kararlar üç yatırım sınıfına ayrılır.','Her kararın kanıt kapısı ve sorumlusu görünür olmalıdır.','Açık konu kapanmadan bağlayıcı tasarım dondurulmamalıdır.'],graphic:{type:'nowPrepareDemand',title:'Konsolide yatırım karar sınıfları',now:['Resmi güç / saha kanıtı','Faz-1 MEP / Cx','Fiber / MMR'],prepare:['Gelecek güç alanı','Liquid headers / CDU alanı','800G / DR / edge interfaces'],demand:['Ek GPU','Wholesale hall','PaaS / DBaaS / edge']},imgs:['board','hall','electrical','cooling'],related:['23','EK-B','EK-C','22']},
    'EK-B':{eyebrow:'KANIT / AÇIK SORU',status:'OPEN ITEMS MASTER',kpis:[['Power','Gate'],['Building','Gate'],['Water','Gate'],['Fiber','Gate']],insight:['Açık sorular risk listesi değil, yatırım karar kapılarıdır.','Her madde için kanıt, sorumlu, tarih ve kapanış kriteri tanımlanmalıdır.','H3C teyitleri ile saha mühendislik teyitleri ayrı tutulmalıdır.'],graphic:{type:'gates',title:'Kritik kanıt kapıları',items:[['Power','Connection / fault level'],['Building','Static / seismic / fire'],['Water','Flow / quality / permit'],['Fiber','Route / MMR independence'],['Tier/Cx','Scope / test plan'],['IT/H3C','BoQ / HCL / support']]},imgs:['electrical','cooling','fiber','hall'],related:['23','EK-A','EK-C','12']},
    'EK-C':{eyebrow:'H3C ÇÖZÜM EŞLEŞTİRMESİ',status:'TECHNICAL CANDIDATE / WRITTEN CONFIRMATION REQUIRED',kpis:[['IC8000','Physical'],['UIS/CAS','HCI'],['CloudOS','Cloud'],['AD-DC','Network']],insight:['H3C’nin ana avantajı uçtan uca entegrasyon ve Day-2 operasyon sadeliğidir.','Her kategoride mutlak üstünlük iddiası yapılmamalıdır.','Exact model, edition, license, HCL, lifecycle, Türkiye SLA ve SPQ yazılı teyit edilmelidir.'],graphic:{type:'valueStack',title:'H3C full-stack aday eşleştirmesi',layers:[['Physical','IC8000 / DCIM'],['Compute/HCI','UIS 3000 G6 / CAS / ONEStor'],['Cloud','CloudOS'],['Network','Spine-leaf / AD-DC / SeerEngine'],['Operations','Common management + single escalation']]},imgs:['hall','noc','board','electrical'],related:['13','10','09','16']},
    'EK-D':{eyebrow:'AKRONİM SÖZLÜĞÜ',status:'REFERENCE',kpis:[['MEP','Facility'],['HCI','Infrastructure'],['RPO/RTO','Recovery'],['PUE/WUE','Sustainability']],insight:['Kısaltmalar bölüm bağlamında okunmalıdır.','Vendor isimleri ile endüstri terimleri ayrılmalıdır.','Sözlük karar, teklif veya teknik onay yerine geçmez.'],graphic:{type:'terms',title:'Terim aileleri',groups:[['Facility','MEP • UPS • PDU • CDU'],['IT','HCI • VDC • EVPN/VXLAN'],['Resilience','HA • AZ • DR • RPO/RTO'],['Operations','DCIM • BMS • EMS • NMS • NOC • SOC'],['Efficiency','PUE • WUE • CUE']]},imgs:['noc','electrical','cooling','fiber'],related:['03','08','09','16']},
    'EK-E':{eyebrow:'KAYNAKÇA',status:'SOURCE REGISTER',kpis:[['Primary','Project baseline'],['Vendor','Datasheets'],['Standards','External'],['Evidence','Versioned']],insight:['Kaynağın tarihi ve sürümü teknik karar kadar önemlidir.','Vendor içeriği bağımsız standart / saha kanıtı yerine geçmez.','Gizli / Secret H3C materyali müşteri yayınına doğrudan taşınmamalıdır.'],graphic:{type:'sourcePyramid',title:'Kanıt önceliği',items:['Son açık yönetim kararı','Son H3C yazılı teyidi','Son H3C sunumu / DWG','Doğrulanmış saha raporu','Güncel BOM / SPQ / BoQ','Master takvim','Türetilmiş analiz / eski sunum']},imgs:['board','meeting','hall','noc'],related:['EK-F','EK-B','EK-C','23']},
    'EK-F':{eyebrow:'PROGRAM CONTROL',status:'REVISION CONTROL',kpis:[['Source','Traceable'],['Old/New','Recorded'],['Reason','Required'],['Date','Versioned']],insight:['Eski değerler sessizce silinmemelidir.','Kaynak, tarih, eski/yeni değer ve değişiklik nedeni revizyon kaydında tutulmalıdır.','Çelişkide tanımlı kaynak önceliği uygulanmalıdır.'],graphic:{type:'revision',title:'Revizyon kayıt zinciri',items:[['Kaynak','Nereden geldi?'],['Eski değer','Ne değişti?'],['Yeni değer','Güncel baseline'],['Neden','Değişiklik gerekçesi'],['Tarih / onay','Kim / ne zaman?']]},imgs:['executive','board','noc','hall'],related:['23','EK-B','EK-E','01']}
  };
  const FALLBACK=P['00'];
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
  function profileFor(c){return P[c.id]||FALLBACK;}
  function chapterByTitle(){const t=(document.getElementById('readerTitle')||{}).textContent||'';return guide.chapters.find(c=>c.title===t)||guide.chapters[0];}
  function chapterById(id){return guide.chapters.find(c=>String(c.id).toUpperCase()===String(id).toUpperCase());}
  function hashFor(id){return '#bolum-'+String(id).toLocaleLowerCase('tr-TR').replace(/[^a-z0-9ğüşöçı-]+/g,'-');}
  function box(a,b,c=''){return '<div class="gbox"><b>'+esc(a)+'</b><span>'+esc(b)+'</span>'+(c?'<small>'+esc(c)+'</small>':'')+'</div>';}
  function graphicHTML(g){
    const title='<div class="exec-graphic-head"><div><span>ANA AÇIKLAYICI GRAFİK</span><h3>'+esc(g.title)+'</h3></div><small>Concept / decision-support</small></div>';let body='';
    if(g.type==='valueStack')body='<div class="g-stack">'+g.layers.map((x,i)=>'<div><em>'+String(i+1).padStart(2,'0')+'</em>'+box(x[0],x[1])+'</div>').join('')+'</div>';
    else if(g.type==='compare3')body='<div class="g-compare3">'+g.cols.map(x=>'<div><h4>'+esc(x[0])+'</h4><p>'+esc(x[1])+'</p><p>'+esc(x[2])+'</p><strong>'+esc(x[3])+'</strong></div>').join('')+'</div>';
    else if(g.type==='powerDual')body='<div class="g-power"><div class="power-lane a">'+g.a.map(x=>box(x,'A yolu')).join('<i>→</i>')+'</div><div class="power-lane b">'+g.b.map(x=>box(x,'B yolu')).join('<i>→</i>')+'</div><div class="power-end">'+esc(g.end)+'</div></div>';
    else if(g.type==='rideThrough')body='<div class="g-sequence">'+g.items.map((x,i)=>'<div><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span><em>'+String(i+1)+'</em></div>').join('')+'</div>';
    else if(g.type==='distribution')body='<div class="g-distribution"><div class="root">'+esc(g.root)+'</div><div class="branches">'+g.branches.map(x=>'<div>'+box(x[0],x[1])+'</div>').join('')+'</div><div class="loads">'+g.loads.map(x=>box(x[0],x[1])).join('')+'</div></div>';
    else if(g.type==='batteryRoles')body='<div class="g-cards">'+g.items.map(x=>'<div>'+box(x[0],x[1],x[2])+'</div>').join('')+'</div>';
    else if(g.type==='steps')body='<div class="g-steps">'+g.items.map((x,i)=>'<div><em>'+String(i+1).padStart(2,'0')+'</em><span>'+esc(x)+'</span></div>').join('')+'</div>';
    else if(g.type==='coolingDual')body='<div class="g-cooling"><div class="cool-lane air"><h4>HAVA SOĞUTMALI ZON</h4>'+g.air.map(x=>box(x,'')).join('')+'</div><div class="cool-source"><h4>KAYNAK / ISI REDDİ</h4>'+g.source.map(x=>box(x,'')).join('')+'</div><div class="cool-lane liquid"><h4>SIVI SOĞUTMALI ZON</h4>'+g.liquid.map(x=>box(x,'')).join('')+'</div></div>';
    else if(g.type==='network')body='<div class="g-network"><div class="net-edge left">'+g.left.map(x=>box(x,'')).join('')+'</div><div class="net-core">'+g.core.map(x=>box(x,'Core')).join('')+'<div class="net-leaf">'+g.leaf.map(x=>box(x,'Access')).join('')+'</div><strong>'+esc(g.end)+'</strong></div><div class="net-edge right">'+g.right.map(x=>box(x,'')).join('')+'</div></div>';
    else if(g.type==='cloudStack')body='<div class="g-cloud"><div class="cloud-row top">'+g.top.map(x=>box(x,'')).join('')+'</div><div class="cloud-row mid">'+g.mid.map(x=>box(x,'')).join('')+'</div><div class="cloud-row platform">'+g.platform.map(x=>box(x,'')).join('')+'</div><div class="cloud-row infra">'+g.infra.map(x=>box(x,'')).join('')+'</div><div class="cloud-bottom">'+esc(g.bottom)+'</div></div>';
    else if(g.type==='coloStack')body='<div class="g-colo">'+g.items.map((x,i)=>'<div><em>'+String(i+1).padStart(2,'0')+'</em><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('')+'</div>';
    else if(g.type==='gates')body='<div class="g-gates">'+g.items.map((x,i)=>'<div><em>'+String(i+1)+'</em><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('')+'</div>';
    else if(g.type==='hci')body='<div class="g-hci"><div class="hci-nodes">'+g.nodes.map(x=>box(x[0],x[1])).join('')+'</div><div class="hci-layers">'+g.layers.map((x,i)=>'<div><em>'+String(i+1)+'</em><span>'+esc(x)+'</span></div>').join('')+'</div></div>';
    else if(g.type==='failureDomains')body='<div class="g-domains">'+g.items.map((x,i)=>'<div class="domain d'+i+'"><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('')+'<p>'+esc(g.arrow)+'</p></div>';
    else if(g.type==='recovery')body='<div class="g-recovery">'+g.items.map((x,i)=>'<div><em>'+String(i+1)+'</em>'+box(x[0],x[1])+'</div>').join('')+'</div>';
    else if(g.type==='ops')body='<div class="g-ops"><div><h4>SOURCES</h4>'+g.sources.map(x=>box(x,'')).join('')+'</div><i>→</i><div><h4>PLATFORMS</h4>'+g.platform.map(x=>box(x,'')).join('')+'</div><i>→</i><div><h4>OPERATIONS</h4>'+g.ops.map(x=>box(x,'')).join('')+'</div></div>';
    else if(g.type==='securityRings')body='<div class="g-security">'+g.rings.map((x,i)=>'<div class="ring r'+i+'"><span>'+esc(x)+'</span></div>').join('')+'</div>';
    else if(g.type==='aiPod')body='<div class="g-ai">'+g.items.map((x,i)=>'<div><em>'+String(i+1).padStart(2,'0')+'</em>'+box(x[0],x[1])+'</div>').join('')+'<strong>'+esc(g.footer)+'</strong></div>';
    else if(g.type==='sustain')body='<div class="g-sustain">'+g.items.map((x,i)=>'<div><em>'+String(i+1)+'</em><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('')+'</div>';
    else if(g.type==='edge')body='<div class="g-edge"><div class="edge-hub">'+esc(g.hub)+'</div><div class="edge-links">'+g.spokes.map(x=>box(x[0],x[1])).join('')+'</div><strong>'+esc(g.links)+'</strong></div>';
    else if(g.type==='nowPrepareDemand')body='<div class="g-npd"><div><h4>BUGÜN</h4>'+g.now.map(x=>'<span>'+esc(x)+'</span>').join('')+'</div><div><h4>HAZIRLA</h4>'+g.prepare.map(x=>'<span>'+esc(x)+'</span>').join('')+'</div><div><h4>TALEP İLE</h4>'+g.demand.map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></div>';
    else if(g.type==='finance')body='<div class="g-finance">'+g.items.map((x,i)=>'<div style="--w:'+(58+i*7)+'%"><em>'+String(i+1)+'</em><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('')+'</div>';
    else if(g.type==='roadmap')body='<div class="g-roadmap">'+g.items.map((x,i)=>'<div><em>'+String(i+1)+'</em><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('')+'</div>';
    else if(g.type==='terms')body='<div class="g-terms">'+g.groups.map(x=>'<div><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('')+'</div>';
    else if(g.type==='sourcePyramid')body='<div class="g-pyramid">'+g.items.map((x,i)=>'<div style="--w:'+(100-i*7)+'%"><em>'+String(i+1)+'</em><span>'+esc(x)+'</span></div>').join('')+'</div>';
    else if(g.type==='revision')body='<div class="g-revision">'+g.items.map((x,i)=>'<div><em>'+String(i+1)+'</em><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('')+'</div>';
    return '<section class="exec-graphic">'+title+body+'</section>';
  }
  function carouselHTML(p){const slides=p.imgs.map((key,i)=>{const img=G[key];return '<div class="chapter-slide" data-i="'+i+'"><img src="'+img[0]+'" alt="'+esc(img[1])+'" loading="lazy"><div class="chapter-slide-copy"><strong>'+esc(img[1])+'</strong><span>Destekleyici konsept görsel · uygulama projesi değildir</span></div></div>';}).join('');return '<section class="chapter-carousel"><div class="chapter-carousel-track">'+slides+'</div><div class="chapter-carousel-top"><span class="chapter-carousel-tag">DESTEKLEYİCİ GÖRSELLER</span><span class="chapter-carousel-count">1 / '+p.imgs.length+'</span></div><div class="chapter-carousel-dots">'+p.imgs.map((_,i)=>'<button type="button" data-slide="'+i+'" class="'+(i===0?'is-active':'')+'" aria-label="Görsel '+(i+1)+'"></button>').join('')+'</div><div class="chapter-carousel-controls"><button type="button" data-dir="prev" aria-label="Önceki görsel">‹</button><button type="button" data-dir="next" aria-label="Sonraki görsel">›</button></div></section>';}
  function linksHTML(c,p){const related=(p.related||[]).map(chapterById).filter(Boolean);const internal=related.map(x=>'<a class="chapter-deep-link" href="'+hashFor(x.id)+'" data-chapter-id="'+esc(x.id)+'"><span>'+esc(x.id)+' · '+esc(x.title)+'</span><b>→</b></a>').join('');const docs='<a class="chapter-doc-link" href="assets/KAYAS_DC_Yatirim_ve_Teknoloji_Rehberi_v3.2_Editorial_Editable_Final.pdf" target="_blank" rel="noopener"><span>PDF rehber</span><b>↗</b></a><a class="chapter-doc-link" href="assets/KAYAS_DC_Yatirim_ve_Teknoloji_Rehberi_v3.2_Editorial_Editable_Final.docx" download><span>DOCX kaynak</span><b>↓</b></a><a class="chapter-doc-link" href="../"><span>KAYAS ana portal</span><b>↗</b></a>';return '<section class="chapter-links"><div class="chapter-links-head"><strong>İlgili bölümler ve kaynaklar</strong><span>Tıklanabilir navigasyon</span></div><div class="chapter-link-row">'+internal+docs+'</div></section>';}
  function renderExecutive(c){const p=profileFor(c);return '<div class="chapter-executive chapter-executive-v2" data-chapter="'+esc(c.id)+'"><section class="exec-summary"><div class="exec-summary-head"><div><span>'+esc(p.eyebrow)+'</span><h3>Yönetici özeti</h3></div><strong>'+esc(p.status)+'</strong></div><div class="exec-kpis">'+p.kpis.map(x=>'<div class="exec-kpi"><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('')+'</div></section>'+graphicHTML(p.graphic)+'<aside class="exec-insight"><div><span>YÖNETİCİ OKUMASI</span><h3>Bu bölümden hangi karar çıkar?</h3></div><ul>'+p.insight.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><div class="exec-status"><b>'+esc(p.status)+'</b><span>Bu panel rehberdeki bilgi statülerini ve çalışma baseline’ını görünür kılar.</span></div></aside>'+carouselHTML(p)+linksHTML(c,p)+'</div>';}
  let carouselTimer=null;function stopCarousel(){if(carouselTimer){clearInterval(carouselTimer);carouselTimer=null;}}
  function initCarousel(root){stopCarousel();const track=root.querySelector('.chapter-carousel-track'),slides=[...root.querySelectorAll('.chapter-slide')],dots=[...root.querySelectorAll('.chapter-carousel-dots button')],count=root.querySelector('.chapter-carousel-count');if(!track||!slides.length)return;let i=0;function show(n){i=(n+slides.length)%slides.length;track.style.transform='translateX(-'+(i*100)+'%)';dots.forEach((d,j)=>d.classList.toggle('is-active',j===i));if(count)count.textContent=(i+1)+' / '+slides.length;}root.querySelector('[data-dir="prev"]')?.addEventListener('click',()=>show(i-1));root.querySelector('[data-dir="next"]')?.addEventListener('click',()=>show(i+1));dots.forEach((d,j)=>d.addEventListener('click',()=>show(j)));let sx=0;track.addEventListener('touchstart',e=>{sx=e.touches[0].clientX;},{passive:true});track.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)show(i+(dx<0?1:-1));},{passive:true});root.addEventListener('mouseenter',stopCarousel);root.addEventListener('mouseleave',()=>{carouselTimer=setInterval(()=>show(i+1),7000);});carouselTimer=setInterval(()=>show(i+1),7000);slides.forEach(slide=>slide.querySelector('img')?.addEventListener('click',()=>openFullscreen(slide.querySelector('img').src,slide.querySelector('img').alt)));}
  function openFullscreen(src,alt){let modal=document.getElementById('execFullscreen');if(!modal){modal=document.createElement('div');modal.id='execFullscreen';modal.className='exec-fullscreen';modal.hidden=true;modal.innerHTML='<button type="button" aria-label="Kapat">×</button><img alt="">';document.body.appendChild(modal);modal.querySelector('button').addEventListener('click',()=>modal.hidden=true);modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true;});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.hidden=true;});}modal.querySelector('img').src=src;modal.querySelector('img').alt=alt||'';modal.hidden=false;}
  function navigateToChapter(id,scroll=true){const buttons=[...document.querySelectorAll('#chapterNav .chapter-link')],target=buttons.find(b=>(b.querySelector('b')?.textContent||'').trim().toUpperCase()===String(id).toUpperCase());if(target){target.click();if(scroll)setTimeout(()=>document.getElementById('reader')?.scrollIntoView({behavior:'smooth',block:'start'}),80);return true;}return false;}
  function bindDeepLinks(root){root.querySelectorAll('a[data-chapter-id]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const id=a.dataset.chapterId;history.pushState(null,'',hashFor(id));navigateToChapter(id,true);}));}
  let lastTitle='';function enhance(){const body=document.getElementById('readerBody'),title=document.getElementById('readerTitle');if(!body||!title)return;const c=chapterByTitle();if(!c)return;const stamp=c.id+'|'+title.textContent;if(lastTitle===stamp&&body.querySelector('.chapter-executive-v2'))return;lastTitle=stamp;body.querySelectorAll('.chapter-executive-v2').forEach(x=>x.remove());body.insertAdjacentHTML('afterbegin',renderExecutive(c));const root=body.querySelector('.chapter-executive-v2');initCarousel(root);bindDeepLinks(root);const reader=document.getElementById('reader');if(reader)reader.dataset.chapterId=c.id;if(location.hash!==hashFor(c.id)&&!['#source-panel','#overview','#decisionPanel'].includes(location.hash))history.replaceState(null,'',hashFor(c.id));}
  const observer=new MutationObserver(()=>enhance()),body=document.getElementById('readerBody'),title=document.getElementById('readerTitle');if(body)observer.observe(body,{childList:true,subtree:false});if(title)observer.observe(title,{childList:true,characterData:true,subtree:true});window.addEventListener('hashchange',()=>{const m=location.hash.match(/^#bolum-(.+)$/);if(m)navigateToChapter(m[1],true);});setTimeout(()=>{const m=location.hash.match(/^#bolum-(.+)$/);if(m){navigateToChapter(m[1],false);setTimeout(enhance,50);}else enhance();},120);
})();