(()=>{
'use strict';
if(window.KAYAS_SHELL_RUNTIME)return;window.KAYAS_SHELL_RUNTIME=true;
function current(){const p=location.pathname;if(p.includes('/service-models'))return'service';if(p.includes('/topology'))return'architecture';if(p.includes('investor-edition'))return'investor';if(location.hash==='#three')return'three';return'overview'}
function lang(){return window.KAYAS?.getLang?.()||(document.documentElement.lang||'en').toLowerCase().startsWith('tr')?'tr':'en'}
function labels(l){return l==='tr'?{overview:'Genel Bakış',architecture:'Mimari',service:'Hizmet Modelleri',investor:'Yatırımcı Rehberi',three:'3D Deneyim'}:{overview:'Overview',architecture:'Architecture',service:'Service Models',investor:'Investor Guide',three:'3D Experience'}}
function switchLang(next){window.KAYAS?.setLang?.(next);const p=location.pathname,h=location.hash||'';if(p.endsWith('/investor-edition-en.html')&&next==='tr'){location.href='investor-edition.html'+h;return}if(p.endsWith('/investor-edition.html')&&next==='en'){location.href='investor-edition-en.html'+h;return}document.documentElement.dataset.kayasLang=next;renderLabels();window.dispatchEvent(new CustomEvent('kayas:shell-language',{detail:{lang:next}}));}
function renderLabels(){const l=window.KAYAS?.getLang?.()||lang(),x=labels(l),s=document.getElementById('kayasExperienceShell');if(!s)return;s.querySelectorAll('[data-kx-label]').forEach(a=>a.textContent=x[a.dataset.kxLabel]||a.textContent);s.querySelectorAll('.kx-lang button').forEach(b=>b.classList.toggle('on',b.dataset.lang===l));}
function build(){if(document.getElementById('kayasExperienceShell'))return;const l=window.KAYAS?.getLang?.()||lang(),x=labels(l),active=current();const shell=document.createElement('div');shell.id='kayasExperienceShell';shell.innerHTML=`<a class="kx-brand" href="/kayas/"><span class="kx-mark"></span><span>KAYAŞ</span><span style="color:#78919f;font-weight:600;letter-spacing:0">Project Experience</span></a><nav><a data-kx="overview" data-kx-label="overview" href="/kayas/">${x.overview}</a><a data-kx="architecture" data-kx-label="architecture" href="/kayas/topology/">${x.architecture}</a><a data-kx="service" data-kx-label="service" href="/kayas/service-models/">${x.service}</a><a data-kx="investor" data-kx-label="investor" href="${l==='tr'?'/kayas/yatirim_ve_teknoloji_rehberi/investor-edition.html':'/kayas/yatirim_ve_teknoloji_rehberi/investor-edition-en.html'}">${x.investor}</a><a data-kx="three" data-kx-label="three" href="/kayas/#three">${x.three}</a></nav><div class="kx-side"><span class="kx-baseline" data-kayas="capacity.itCabinetsTotal">210</span><span class="kx-baseline">IT ·</span><span class="kx-baseline" data-kayas="capacity.workingDesignITLoadMW" data-kayas-format="mw">2.00 MW</span><span class="kx-lang"><button data-lang="tr">TR</button><button data-lang="en">EN</button></span></div>`;shell.querySelector(`[data-kx="${active}"]`)?.classList.add('active');shell.querySelectorAll('.kx-lang button').forEach(b=>b.addEventListener('click',()=>switchLang(b.dataset.lang)));document.body.prepend(shell);document.documentElement.classList.add('kx-page-shift');window.KAYAS?.applyBindings?.(shell);renderLabels();}
function init(){build();window.addEventListener('kayas:data',()=>window.KAYAS?.applyBindings?.(document.getElementById('kayasExperienceShell')));window.addEventListener('kayas:language',renderLabels)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
