(()=>{
'use strict';
if(window.KAYAS_SHELL_RUNTIME)return;window.KAYAS_SHELL_RUNTIME=true;
const THEME_KEY='specbridge_project_theme',PROJECT_DEFAULT='dark',THEME_CSS='/kayas/kayas-theme.css?v=20260901-theme1';
function current(){const p=location.pathname;if(p.includes('/service-models'))return'service';if(p.includes('/topology'))return'architecture';if(p.includes('investor-edition'))return'investor';if(p.includes('/3d/')||location.hash==='#three')return'three';return'overview'}
function lang(){const k=window.KAYAS?.getLang?.();if(k==='tr'||k==='en')return k;return (document.documentElement.lang||'en').toLowerCase().startsWith('tr')?'tr':'en'}
function labels(l){return l==='tr'?{overview:'Genel Bakış',architecture:'Mimari',service:'Hizmet Modelleri',investor:'Yatırımcı Rehberi',three:'3D Deneyim'}:{overview:'Overview',architecture:'Architecture',service:'Service Models',investor:'Investor Guide',three:'3D Experience'}}
function themePref(){try{const v=localStorage.getItem(THEME_KEY);return['light','dark','system'].includes(v)?v:''}catch(_){return''}}
function effectiveTheme(pref=themePref()){if(pref==='light'||pref==='dark')return pref;if(pref==='system')return matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';return PROJECT_DEFAULT}
function ensureThemeCss(){if(document.getElementById('kayasProjectTheme'))return;const l=document.createElement('link');l.id='kayasProjectTheme';l.rel='stylesheet';l.href=THEME_CSS;document.head.appendChild(l)}
function syncFrames(theme){document.querySelectorAll('iframe').forEach(f=>{const apply=()=>{try{f.contentDocument?.documentElement?.setAttribute('data-sb-theme',theme)}catch(_){}};apply();f.addEventListener('load',apply,{once:true})})}
function applyTheme(pref=themePref(),animate=false){ensureThemeCss();const theme=effectiveTheme(pref);if(animate){document.documentElement.classList.add('sb-theme-transition');setTimeout(()=>document.documentElement.classList.remove('sb-theme-transition'),360)}document.documentElement.dataset.sbTheme=theme;document.documentElement.dataset.sbThemePreference=pref||'project';document.documentElement.style.colorScheme=theme;document.querySelectorAll('.kx-theme button').forEach(b=>b.classList.toggle('on',(pref||PROJECT_DEFAULT)===b.dataset.theme));syncFrames(theme);window.dispatchEvent(new CustomEvent('specbridge:theme',{detail:{project:'kayas',preference:pref||'project',theme}}));return theme}
function setTheme(pref){if(!['light','dark','system'].includes(pref))return;try{localStorage.setItem(THEME_KEY,pref)}catch(_){}applyTheme(pref,true)}
function switchLang(next){window.KAYAS?.setLang?.(next);const p=location.pathname,h=location.hash||'';if(p.endsWith('/investor-edition-en.html')&&next==='tr'){location.href='investor-edition.html'+h;return}if(p.endsWith('/investor-edition.html')&&next==='en'){location.href='investor-edition-en.html'+h;return}document.documentElement.dataset.kayasLang=next;renderLabels();window.KAYAS?.applyBindings?.(document);window.dispatchEvent(new CustomEvent('kayas:shell-language',{detail:{lang:next}}));}
function renderLabels(){const l=lang(),x=labels(l),s=document.getElementById('kayasExperienceShell');if(!s)return;s.querySelectorAll('[data-kx-label]').forEach(a=>a.textContent=x[a.dataset.kxLabel]||a.textContent);const inv=s.querySelector('[data-kx="investor"]');if(inv)inv.href=l==='tr'?'/kayas/yatirim_ve_teknoloji_rehberi/investor-edition.html':'/kayas/yatirim_ve_teknoloji_rehberi/investor-edition-en.html';s.querySelectorAll('.kx-lang button').forEach(b=>b.classList.toggle('on',b.dataset.lang===l));}
function build(){if(document.getElementById('kayasExperienceShell'))return;const l=lang(),x=labels(l),active=current(),pref=themePref()||PROJECT_DEFAULT;const shell=document.createElement('div');shell.id='kayasExperienceShell';shell.innerHTML=`<a class="kx-brand" href="/kayas/"><span class="kx-mark"></span><span>KAYAŞ</span><span style="color:#78919f;font-weight:600;letter-spacing:0">Project Experience</span></a><nav><a data-kx="overview" data-kx-label="overview" href="/kayas/">${x.overview}</a><a data-kx="architecture" data-kx-label="architecture" href="/kayas/topology/#view=K00">${x.architecture}</a><a data-kx="service" data-kx-label="service" href="/kayas/service-models/">${x.service}</a><a data-kx="investor" data-kx-label="investor" href="${l==='tr'?'/kayas/yatirim_ve_teknoloji_rehberi/investor-edition.html':'/kayas/yatirim_ve_teknoloji_rehberi/investor-edition-en.html'}">${x.investor}</a><a data-kx="three" data-kx-label="three" href="/kayas/3d/">${x.three}</a></nav><div class="kx-side"><span class="kx-baseline" data-kayas="capacity.itCabinetsTotal">210</span><span class="kx-baseline">IT ·</span><span class="kx-baseline" data-kayas="capacity.workingDesignITLoadMW" data-kayas-format="mw">2.00 MW</span><span class="kx-theme" aria-label="Theme"><button data-theme="light" title="Light theme" aria-label="Light theme">L</button><button data-theme="dark" title="Dark theme" aria-label="Dark theme">D</button><button data-theme="system" title="System theme" aria-label="System theme">S</button></span><span class="kx-lang"><button data-lang="tr">TR</button><button data-lang="en">EN</button></span></div>`;shell.querySelector(`[data-kx="${active}"]`)?.classList.add('active');shell.querySelectorAll('.kx-lang button').forEach(b=>b.addEventListener('click',()=>switchLang(b.dataset.lang)));shell.querySelectorAll('.kx-theme button').forEach(b=>b.addEventListener('click',()=>setTheme(b.dataset.theme)));shell.querySelectorAll('.kx-theme button').forEach(b=>b.classList.toggle('on',b.dataset.theme===pref));document.body.prepend(shell);document.documentElement.classList.add('kx-page-shift');window.KAYAS?.applyBindings?.(shell);renderLabels();applyTheme(themePref());}
function init(){ensureThemeCss();applyTheme(themePref());build();window.addEventListener('kayas:data',()=>window.KAYAS?.applyBindings?.(document.getElementById('kayasExperienceShell')));window.addEventListener('kayas:language',()=>{renderLabels();window.KAYAS?.applyBindings?.(document)});matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>{if(themePref()==='system')applyTheme('system',true)});new MutationObserver(()=>syncFrames(effectiveTheme())).observe(document.body,{childList:true,subtree:true})}
window.KAYAS_THEME={getPreference:themePref,getEffective:effectiveTheme,set:setTheme,apply:applyTheme};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
