(()=>{
'use strict';
const DATA=window.DATACENTER_BRIEFING, SYNC=window.DATACENTER_AUDIO_SYNC;
if(!DATA||!SYNC||!SYNC.chapters)return;
for(const c of DATA.chapters){const s=SYNC.chapters[c.id];if(s)Object.assign(c,{audio:s.audio,vtt:s.vtt,duration:s.duration,segments:s.segments,cues:s.cues});}
const READY=DATA.chapters.length===15&&DATA.chapters.every(c=>c.audio&&Array.isArray(c.cues)&&c.cues.length&&Array.isArray(c.segments)&&c.segments.length);
const KEY='specbridge_datacenter_briefing_v2_state', THEME_KEY='specbridge_project_theme';
const state={chapter:0,segment:0,playing:false,mode:'listen',rate:1,autoNext:true,time:0};
const audio=new Audio();audio.preload='metadata';let loadedChapter=-1,lastSave=0,pendingSeek=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function chapter(){return DATA.chapters[state.chapter]}
function loadState(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');if(Number.isInteger(s.chapter))state.chapter=Math.max(0,Math.min(DATA.chapters.length-1,s.chapter));if(Number.isInteger(s.segment))state.segment=Math.max(0,s.segment);if(typeof s.rate==='number')state.rate=s.rate;if(typeof s.time==='number')state.time=Math.max(0,s.time);if(s.mode)state.mode=s.mode;if(typeof s.autoNext==='boolean')state.autoNext=s.autoNext}catch(_){}}
function saveState(force=false){const now=Date.now();if(!force&&now-lastSave<3000)return;lastSave=now;try{localStorage.setItem(KEY,JSON.stringify({chapter:state.chapter,segment:state.segment,rate:state.rate,mode:state.mode,autoNext:state.autoNext,time:audio.currentTime||state.time||0}))}catch(_){}}
function prefTheme(){try{const p=localStorage.getItem(THEME_KEY);return['light','dark','system'].includes(p)?p:'dark'}catch(_){return'dark'}}
function effectiveTheme(p=prefTheme()){return p==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):p}
function applyTheme(p=prefTheme()){document.documentElement.dataset.theme=effectiveTheme(p);$$('[data-theme]').forEach(b=>b.classList.toggle('on',b.dataset.theme===p));const m=document.querySelector('meta[name="theme-color"]');if(m)m.content=effectiveTheme(p)==='dark'?'#061018':'#edf3f6'}
function setTheme(p){try{localStorage.setItem(THEME_KEY,p)}catch(_){}applyTheme(p)}
function cueFor(seg=state.segment,c=chapter()){return c.cues?.find(x=>x.segment===seg)||c.cues?.[seg]||null}
function segmentForTime(t,c=chapter()){let found=0;for(const cue of c.cues||[]){if(t>=cue.start)found=cue.segment??found;if(t>=cue.start&&t<(cue.end??Infinity))return cue.segment??found}return found}
function renderChapters(){const host=$('#chapterList');host.innerHTML=DATA.chapters.map((c,i)=>`<button class="chapter-item ${i===state.chapter?'active':''}" data-i="${i}"><span>${c.id}</span><div><b>${esc(c.title)}</b><small>${esc(c.kicker)} · ${c.segments.length} altyazı · mastered</small></div></button>`).join('');host.onclick=e=>{const b=e.target.closest('.chapter-item');if(b)openChapter(+b.dataset.i,0,false)};}
function renderTranscript(){const c=chapter(),host=$('#transcript');host.innerHTML=c.segments.map((s,i)=>`<button class="transcript-line ${i===state.segment?'active':''}" data-s="${i}"><span>${String(i+1).padStart(2,'0')}</span><p>${esc(s)}</p></button>`).join('');host.onclick=e=>{const b=e.target.closest('.transcript-line');if(b)seekSegment(+b.dataset.s,true)};}
function renderSources(){const c=chapter(),host=$('#sourceList');host.innerHTML=(c.sources||[]).map(k=>{const s=DATA.sources[k];return s?`<a class="source-card" href="${esc(s.url)}" target="_blank" rel="noopener"><span>OFFICIAL / PRIMARY SOURCE</span><b>${esc(s.name)}</b><strong>${esc(s.title)}</strong><p>${esc(s.note)}</p><em>Kaynağı aç ↗</em></a>`:''}).join('');}
function renderVisual(){const c=chapter(),v=$('#visual');const H={
systems:`<div class="visual-title">DATA CENTER = SYSTEM OF SYSTEMS</div><div class="systems"><i>POWER</i><i>COOLING</i><i>NETWORK</i><i>SECURITY</i><i>OPERATIONS</i><b>IT CAPACITY</b></div><p>Kabinet yalnızca görünen son noktadır.</p>`,
demand:`<div class="visual-title">GLOBAL CAPACITY DEMAND · SCENARIO</div><div class="bars"><div><b style="height:37%"></b><span>2025</span><strong>~82 GW</strong></div><div><b style="height:100%"></b><span>2030</span><strong>~220 GW</strong></div></div><p>McKinsey orta-senaryo büyüklükleri; tahmindir, garanti edilmiş talep değildir.</p>`,
ai:`<div class="visual-title">AI CHANGES DENSITY</div><div class="density"><div><b>STANDARD IT</b><strong>Air / hybrid</strong><span>efficient general-purpose capacity</span></div><div class="hot"><b>AI / GPU</b><strong>High-density</strong><span>power · liquid/hybrid cooling · fabric</span></div></div>`,
energy:`<div class="visual-title">DATA-CENTER ELECTRICITY DEMAND</div><div class="bars energy"><div><b style="height:51%"></b><span>2025</span><strong>~485 TWh</strong></div><div><b style="height:100%"></b><span>2030</span><strong>~950 TWh</strong></div></div><p>IEA central outlook context.</p>`,
power:`<div class="visual-title">POWER CHAIN</div><div class="chain"><span>GRID / GEN</span><i>→</i><span>TRANSFORMER</span><i>→</i><span>SWITCHGEAR</span><i>→</i><span>UPS</span><i>→</i><span>DISTRIBUTION</span><i>→</i><b>RACK</b></div>`,
cooling:`<div class="visual-title">THERMAL CHAIN</div><div class="chain"><span>CHIP</span><i>→</i><span>SERVER</span><i>→</i><span>RACK</span><i>→</i><span>ROOM</span><i>→</i><span>COOLING</span><i>→</i><b>HEAT REJECTION</b></div>`,
network:`<div class="visual-title">INTERCONNECTION ECONOMY</div><div class="network-map"><b>DATA CENTER</b><span>Carrier A</span><span>Carrier B</span><span>IX</span><span>Cloud</span><span>DCI</span><span>OOB</span></div><p>Değer yalnız içerideki IT'den değil, bağlantı seçeneklerinden de gelir.</p>`,
security:`<div class="visual-title">DEFENSE IN DEPTH</div><div class="rings"><div>PERIMETER<div>ACCESS<div>NETWORK<div>IDENTITY<div>DATA</div></div></div></div></div>`,
operations:`<div class="visual-title">OPERATIONS LIFECYCLE</div><div class="loop"><span>MONITOR</span><i>→</i><span>OPERATE</span><i>→</i><span>MAINTAIN</span><i>→</i><span>CHANGE</span><i>→</i><span>LEARN</span></div><div class="ops-tags"><b>SOP</b><b>MOP</b><b>EOP</b><b>DCIM</b><b>BMS</b><b>EPMS</b></div>`,
commissioning:`<div class="visual-title">INTEGRATED SYSTEMS TESTING</div><div class="test-grid"><span>UTILITY LOSS</span><span>UPS HOLD</span><span>GEN START</span><span>COOLING STABLE</span><span>NETWORK AVAILABLE</span><span>ALARMS CORRECT</span></div><strong class="center-note">The question is not “does each device work?” — it is “does the facility work together?”</strong>`,
advisory:`<div class="visual-title">OWNER'S TECHNICAL GOVERNANCE</div><div class="advisory"><span>POWER VENDOR</span><span>COOLING VENDOR</span><span>NETWORK VENDOR</span><span>CONTRACTOR</span><b>INDEPENDENT ADVISER</b><strong>INVESTOR</strong></div><p>Danışman ürünün değil, yatırım kararının teknik temsilcisidir.</p>`,
turkey:`<div class="visual-title">WHY TÜRKİYE?</div><div class="stats"><div><b>86M+</b><span>large domestic market</span></div><div><b>90%+</b><span>internet usage</span></div><div><b>IST</b><span>regional interconnection</span></div><div><b>AWS</b><span>Istanbul Local Zone</span></div><div><b>Google</b><span>Türkiye cloud region plan</span></div><div><b>AI/DC</b><span>policy & investment interest</span></div></div>`,
whynow:`<div class="visual-title">WHY NOW?</div><div class="why-now"><span>GLOBAL COMPUTE DEMAND ↑</span><span>POWER SCARCITY IN MATURE HUBS</span><span>TÜRKİYE INTERCONNECTION ↑</span><span>HYPERSCALER SIGNALS ↑</span><b>PHASED OPPORTUNITY WINDOW</b></div>`,
phases:`<div class="visual-title">PHASED CAPITAL DISCIPLINE</div><div class="phases"><span>MASTERPLAN</span><i>→</i><span>PHASE 1</span><i>→</i><span>ANCHOR / PRE-LEASE</span><i>→</i><span>EXPAND</span><i>→</i><b>SCALE</b></div><p>Nihai vizyon ile ilk gün CAPEX aynı olmak zorunda değildir.</p>`,
closing:`<div class="visual-title">THE INVESTMENT EQUATION</div><div class="closing"><span>SECURED POWER</span><b>+</b><span>CONNECTIVITY</span><b>+</b><span>DEMAND</span><b>+</b><span>ENGINEERING</span><b>+</b><span>OPERATIONS</span></div><strong class="closing-line">= STRATEGIC DIGITAL INFRASTRUCTURE</strong>`};v.innerHTML=H[c.visual]||H.systems;}
function renderAll(){renderChapters();renderTranscript();renderSources();renderVisual();updateCurrent(true)}
function ensureAudio(){const c=chapter();if(loadedChapter!==state.chapter){audio.pause();audio.src=c.audio;audio.load();loadedChapter=state.chapter;}audio.playbackRate=state.rate;}
function safeSeek(t){pendingSeek=Math.max(0,Number(t)||0);try{audio.currentTime=pendingSeek;pendingSeek=null}catch(_){}}
function updateMedia(){if(!('mediaSession'in navigator))return;const c=chapter();try{navigator.mediaSession.metadata=new MediaMetadata({title:c.title,artist:'SpecBridge · Data Center Investment Briefing',album:'Professional Turkish Narration · S3F'});navigator.mediaSession.playbackState=audio.paused?'paused':'playing';if(typeof navigator.mediaSession.setPositionState==='function'&&Number.isFinite(audio.duration)&&audio.duration>0){navigator.mediaSession.setPositionState({duration:audio.duration,playbackRate:audio.playbackRate||1,position:Math.max(0,Math.min(audio.duration,audio.currentTime||0))})}}catch(_){} }
function updateCurrent(force=false){const c=chapter();state.segment=Math.max(0,Math.min(c.segments.length-1,state.segment));$('#chapterNo').textContent=`CHAPTER ${c.id}`;$('#chapterTitle').textContent=c.title;$('#chapterSummary').textContent=c.summary;$('#subtitle').textContent=c.segments[state.segment]||'';const pct=c.duration?Math.min(100,(audio.currentTime/c.duration)*100):0;$('#progressFill').style.width=`${pct}%`;$('#progressText').textContent=`${state.chapter+1}/${DATA.chapters.length} · ${fmtTime(audio.currentTime)} / ${fmtTime(c.duration)}`;$$('.chapter-item').forEach((b,i)=>b.classList.toggle('active',i===state.chapter));$$('.transcript-line').forEach((b,i)=>b.classList.toggle('active',i===state.segment));if(force)$('.transcript-line.active')?.scrollIntoView({block:'nearest'});saveState();updateMedia();}
function fmtTime(s){s=Math.max(0,Math.floor(Number(s)||0));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function syncPlay(){const b=$('#playBtn');b.textContent=audio.paused?'▶ Dinle':'Ⅱ Duraklat';b.classList.toggle('playing',!audio.paused);state.playing=!audio.paused;updateMedia();}
function seekSegment(seg,play=false){state.segment=Math.max(0,Math.min(chapter().segments.length-1,seg));ensureAudio();const cue=cueFor();safeSeek(cue?cue.start:0);updateCurrent(true);if(play)audio.play().catch(()=>{});}
function openChapter(i,seg=0,play=false){const wasPlaying=play||!audio.paused;audio.pause();state.chapter=Math.max(0,Math.min(DATA.chapters.length-1,i));state.segment=Math.max(0,seg);loadedChapter=-1;ensureAudio();const cue=cueFor();safeSeek(cue?.start||0);renderAll();if(wasPlaying)audio.play().catch(()=>{});closeMobilePanels();}
function playPause(){if(!READY)return;if(audio.paused){ensureAudio();audio.play().catch(()=>{})}else audio.pause()}
function stop(){audio.pause();const cue=cueFor();safeSeek(cue?.start||0);updateCurrent(true)}
function next(){const c=chapter();if(state.segment<c.segments.length-1)seekSegment(state.segment+1,!audio.paused);else if(state.chapter<DATA.chapters.length-1)openChapter(state.chapter+1,0,!audio.paused)}
function prev(){if(state.segment>0)seekSegment(state.segment-1,!audio.paused);else if(state.chapter>0){const c=DATA.chapters[state.chapter-1];openChapter(state.chapter-1,c.segments.length-1,!audio.paused)}}
function setMode(mode){state.mode=mode;document.body.dataset.mode=mode;$$('[data-mode]').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode));saveState(true)}
function closeMobilePanels(){document.body.classList.remove('chapters-open','side-open')}
function bind(){
 $('#playBtn').onclick=playPause;$('#stopBtn').onclick=stop;$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;
 $('#rate').value=String(state.rate);$('#rate').onchange=e=>{state.rate=+e.target.value||1;audio.playbackRate=state.rate;saveState(true)};
 $('#autoNext').checked=state.autoNext;$('#autoNext').onchange=e=>{state.autoNext=e.target.checked;saveState(true)};
 $$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));
 $('#menuBtn').onclick=()=>document.body.classList.toggle('chapters-open');$('#closePanels').onclick=closeMobilePanels;
 audio.addEventListener('play',syncPlay);audio.addEventListener('pause',syncPlay);audio.addEventListener('ended',()=>{if(state.autoNext&&state.chapter<DATA.chapters.length-1)openChapter(state.chapter+1,0,true);else syncPlay()});
 audio.addEventListener('timeupdate',()=>{const seg=segmentForTime(audio.currentTime);if(seg!==state.segment){state.segment=seg;updateCurrent(true)}else updateCurrent(false)});
 audio.addEventListener('loadedmetadata',()=>{if(pendingSeek!==null)safeSeek(pendingSeek);updateCurrent(false)});
 window.addEventListener('beforeunload',()=>saveState(true));
 if('mediaSession'in navigator){try{navigator.mediaSession.setActionHandler('play',()=>audio.play());navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('previoustrack',prev);navigator.mediaSession.setActionHandler('nexttrack',next);navigator.mediaSession.setActionHandler('seekbackward',d=>safeSeek(Math.max(0,audio.currentTime-(d.seekOffset||15))));navigator.mediaSession.setActionHandler('seekforward',d=>safeSeek(Math.min(chapter().duration,audio.currentTime+(d.seekOffset||15))));navigator.mediaSession.setActionHandler('seekto',d=>{if(typeof d.seekTime==='number')safeSeek(Math.max(0,Math.min(chapter().duration,d.seekTime)))})}catch(_){} }
}
loadState();applyTheme();setMode(state.mode);ensureAudio();const c=chapter();state.segment=Math.min(state.segment,c.segments.length-1);const saved=state.time;if(saved>0&&saved<c.duration){safeSeek(saved);state.segment=segmentForTime(saved,c)}else{const cue=cueFor();safeSeek(cue?.start||0);}renderAll();bind();syncPlay();
const voiceStatus=$('#voiceStatus');if(voiceStatus)voiceStatus.textContent=READY?'S3F · Professional Turkish narration · synchronized subtitles':'Mastered audio unavailable';
})();
