(()=>{
'use strict';
const DATA=window.DATACENTER_BRIEFING;if(!DATA)return;
const KEY='specbridge_datacenter_briefing_state',THEME_KEY='specbridge_project_theme';
const state={chapter:0,segment:0,playing:false,mode:'listen',rate:1,voice:null,autoNext:true};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function loadState(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');if(Number.isInteger(s.chapter))state.chapter=Math.max(0,Math.min(DATA.chapters.length-1,s.chapter));if(Number.isInteger(s.segment))state.segment=Math.max(0,s.segment);if(typeof s.rate==='number')state.rate=s.rate;if(s.mode)state.mode=s.mode}catch(_){}}
function saveState(){try{localStorage.setItem(KEY,JSON.stringify({chapter:state.chapter,segment:state.segment,rate:state.rate,mode:state.mode}))}catch(_){}}
function prefTheme(){try{const p=localStorage.getItem(THEME_KEY);return['light','dark','system'].includes(p)?p:'dark'}catch(_){return'dark'}}
function effectiveTheme(p=prefTheme()){if(p==='system')return matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';return p}
function applyTheme(p=prefTheme()){document.documentElement.dataset.theme=effectiveTheme(p);$$('[data-theme]').forEach(b=>b.classList.toggle('on',b.dataset.theme===p));}
function setTheme(p){try{localStorage.setItem(THEME_KEY,p)}catch(_){}applyTheme(p)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderChapters(){const host=$('#chapterList');host.innerHTML=DATA.chapters.map((c,i)=>`<button class="chapter-item ${i===state.chapter?'active':''}" data-i="${i}"><span>${c.id}</span><div><b>${esc(c.title)}</b><small>${esc(c.kicker)} · ${c.segments.length} bölüm</small></div></button>`).join('');host.onclick=e=>{const b=e.target.closest('.chapter-item');if(!b)return;openChapter(+b.dataset.i,0,state.playing)};}
function renderTranscript(){const c=DATA.chapters[state.chapter];const host=$('#transcript');host.innerHTML=c.segments.map((s,i)=>`<button class="transcript-line ${i===state.segment?'active':''}" data-s="${i}"><span>${String(i+1).padStart(2,'0')}</span><p>${esc(s)}</p></button>`).join('');host.onclick=e=>{const b=e.target.closest('.transcript-line');if(!b)return;state.segment=+b.dataset.s;saveState();updateCurrent();if(state.playing)speakCurrent(true)};}
function renderSources(){const c=DATA.chapters[state.chapter];const host=$('#sourceList');host.innerHTML=c.sources.map(k=>{const s=DATA.sources[k];return s?`<a class="source-card" href="${esc(s.url)}" target="_blank" rel="noopener"><span>OFFICIAL / PRIMARY SOURCE</span><b>${esc(s.name)}</b><strong>${esc(s.title)}</strong><p>${esc(s.note)}</p><em>Kaynağı aç ↗</em></a>`:''}).join('');}
function renderVisual(){const c=DATA.chapters[state.chapter],v=$('#visual');const H={
 systems:`<div class="visual-title">DATA CENTER = SYSTEM OF SYSTEMS</div><div class="systems"><i>POWER</i><i>COOLING</i><i>NETWORK</i><i>SECURITY</i><i>OPERATIONS</i><b>IT CAPACITY</b></div><p>Kabinet yalnızca görünen son noktadır.</p>`,
 demand:`<div class="visual-title">GLOBAL CAPACITY DEMAND · SCENARIO</div><div class="bars"><div><b style="height:37%"></b><span>2025</span><strong>~82 GW</strong></div><div><b style="height:100%"></b><span>2030</span><strong>~220 GW</strong></div></div><p>McKinsey orta-senaryo büyüklükleri; tahmindir, garanti edilmiş talep değildir.</p>`,
 ai:`<div class="visual-title">AI CHANGES DENSITY</div><div class="density"><div><b>STANDARD IT</b><strong>Air / hybrid</strong><span>efficient general-purpose capacity</span></div><div class="hot"><b>AI / GPU</b><strong>High-density</strong><span>power · liquid/hybrid cooling · fabric</span></div></div>`,
 energy:`<div class="visual-title">DATA-CENTER ELECTRICITY DEMAND</div><div class="bars energy"><div><b style="height:51%"></b><span>2025</span><strong>~485 TWh</strong></div><div><b style="height:100%"></b><span>2030</span><strong>~950 TWh</strong></div></div><p>IEA central outlook context.</p>`,
 power:`<div class="visual-title">POWER CHAIN</div><div class="chain"><span>GRID / GEN</span><i>→</i><span>TRANSFORMER</span><i>→</i><span>SWITCHGEAR</span><i>→</i><span>UPS</span><i>→</i><span>DISTRIBUTION</span><i>→</i><b>RACK</b></div>`,
 cooling:`<div class="visual-title">THERMAL CHAIN</div><div class="chain"><span>CHIP</span><i>→</i><span>SERVER</span><i>→</i><span>RACK</span><i>→</i><span>ROOM</span><i>→</i><span>COOLING</span><i>→</i><b>HEAT REJECTION</b></div>`,
 network:`<div class="visual-title">INTERCONNECTION ECONOMY</div><div class="network-map"><b>DATA CENTER</b><span>Carrier A</span><span>Carrier B</span><span>IX</span><span>Cloud</span><span>DCI</span><span>OOB</span></div><p>Değer yalnız içerideki IT'den değil, bağlantı seçeneklerinden de gelir.</p>`,
 security:`<div class="visual-title">DEFENSE IN DEPTH</div><div class="rings"><div>PERIMETER<div>ACCESS<div>NETWORK<div>IDENTITY<div>DATA</div></div></div></div></div>`,
 operations:`<div class="visual-title">OPERATIONS LIFECYCLE</div><div class="loop"><span>MONITOR</span><i>→</i><span>OPERATE</span><i>→</i><span>MAINTAIN</span><i>→</i><span>CHANGE</span><i>→</i><span>LEARN</span></div><div class="ops-tags"><b>SOP</b><b>MOP</b><b>EOP</b><b>DCIM</b><b>BMS</b><b>EPMS</b></div>`,
 commissioning:`<div class="visual-title">INTEGRATED SYSTEMS TESTING</div><div class="test-grid"><span>UTILITY LOSS</span><span>UPS HOLD</span><span>GEN START</span><span>COOLING STABLE</span><span>NETWORK AVAILABLE</span><span>ALARMS CORRECT</span></div><strong class="center-note">The question is not “does each device work?” — it is “does the facility work together?”</strong>`,
 advisory:`<div class="visual-title">OWNER'S TECHNICAL GOVERNANCE</div><div class="advisory"><span>POWER VENDOR</span><span>COOLING VENDOR</span><span>NETWORK VENDOR</span><span>CONTRACTOR</span><b>INDEPENDENT ADVISER</b><strong>INVESTOR</strong></div><p>Danışman ürünün değil, yatırım kararının teknik temsilcisidir.</p>`,
 turkey:`<div class="visual-title">WHY TÜRKİYE?</div><div class="stats"><div><b>86M+</b><span>large domestic market</span></div><div><b>90%+</b><span>internet usage</span></div><div><b>IST</b><span>regional interconnection</span></div><div><b>AWS</b><span>Istanbul Local Zone</span></div><div><b>Google</b><span>Türkiye cloud region plan</span></div><div><b>AI/DC</b><span>policy & investment interest</span></div></div>`,
 whynow:`<div class="visual-title">WHY NOW?</div><div class="why-now"><span>GLOBAL COMPUTE DEMAND ↑</span><span>POWER SCARCITY IN MATURE HUBS</span><span>TÜRKİYE INTERCONNECTION ↑</span><span>HYPERSCALER SIGNALS ↑</span><b>PHASED OPPORTUNITY WINDOW</b></div>`,
 phases:`<div class="visual-title">PHASED CAPITAL DISCIPLINE</div><div class="phases"><span>MASTERPLAN</span><i>→</i><span>PHASE 1</span><i>→</i><span>ANCHOR / PRE-LEASE</span><i>→</i><span>EXPAND</span><i>→</i><b>SCALE</b></div><p>Nihai vizyon ile ilk gün CAPEX aynı olmak zorunda değildir.</p>`,
 closing:`<div class="visual-title">THE INVESTMENT EQUATION</div><div class="closing"><span>SECURED POWER</span><b>+</b><span>CONNECTIVITY</span><b>+</b><span>DEMAND</span><b>+</b><span>ENGINEERING</span><b>+</b><span>OPERATIONS</span></div><strong class="closing-line">= STRATEGIC DIGITAL INFRASTRUCTURE</strong>`
 };v.innerHTML=H[c.visual]||H.systems;}
function updateCurrent(){const c=DATA.chapters[state.chapter];state.segment=Math.min(state.segment,c.segments.length-1);$('#chapterNo').textContent=`CHAPTER ${c.id}`;$('#chapterTitle').textContent=c.title;$('#chapterSummary').textContent=c.summary;$('#subtitle').textContent=c.segments[state.segment]||'';$('#progressText').textContent=`${state.chapter+1}/${DATA.chapters.length} · ${state.segment+1}/${c.segments.length}`;const total=DATA.chapters.reduce((n,x)=>n+x.segments.length,0);let done=0;for(let i=0;i<state.chapter;i++)done+=DATA.chapters[i].segments.length;done+=state.segment;$('#progressFill').style.width=`${Math.max(1,(done/(total-1))*100)}%`;$$('.chapter-item').forEach((b,i)=>b.classList.toggle('active',i===state.chapter));$$('.transcript-line').forEach((b,i)=>b.classList.toggle('active',i===state.segment));$('.transcript-line.active')?.scrollIntoView({block:'nearest',behavior:'smooth'});saveState();}
function openChapter(i,s=0,play=false){speechSynthesis.cancel();state.playing=false;state.chapter=Math.max(0,Math.min(DATA.chapters.length-1,i));state.segment=Math.max(0,s);renderChapters();renderTranscript();renderSources();renderVisual();updateCurrent();if(play){state.playing=true;speakCurrent(true)}else syncPlayButton();}
function voices(){return speechSynthesis.getVoices().filter(Boolean)}
function chooseVoice(){const vs=voices();const turkish=vs.filter(v=>/^tr/i.test(v.lang));return turkish.find(v=>/natural|neural|online|premium/i.test(v.name))||turkish[0]||vs[0]||null}
function syncVoiceMenu(){const sel=$('#voiceSelect'),vs=voices();if(!vs.length)return;sel.innerHTML=vs.map((v,i)=>`<option value="${i}">${esc(v.name)} · ${esc(v.lang)}</option>`).join('');const wanted=chooseVoice();const idx=vs.indexOf(wanted);if(idx>=0)sel.value=String(idx);state.voice=wanted;}
function speakCurrent(restart=false){if(!('speechSynthesis'in window)){state.playing=false;syncPlayButton();$('#voiceStatus').textContent='Bu tarayıcı speech synthesis desteklemiyor.';return}if(restart)speechSynthesis.cancel();const c=DATA.chapters[state.chapter],text=c.segments[state.segment];if(!text){state.playing=false;syncPlayButton();return}const u=new SpeechSynthesisUtterance(text);u.lang='tr-TR';u.rate=state.rate;u.pitch=.96;u.volume=1;if(state.voice)u.voice=state.voice;u.onstart=()=>{state.playing=true;syncPlayButton();updateCurrent();$('#voiceStatus').textContent='Canlı TTS fallback · final profesyonel kayıt daha sonra bağlanabilir.'};u.onend=()=>{if(!state.playing)return;if(state.segment<c.segments.length-1){state.segment++;speakCurrent(true)}else if(state.autoNext&&state.chapter<DATA.chapters.length-1){state.chapter++;state.segment=0;renderChapters();renderTranscript();renderSources();renderVisual();speakCurrent(true)}else{state.playing=false;syncPlayButton();}};u.onerror=()=>{state.playing=false;syncPlayButton()};speechSynthesis.speak(u)}
function togglePlay(){if(speechSynthesis.paused){speechSynthesis.resume();state.playing=true;syncPlayButton();return}if(state.playing){speechSynthesis.pause();state.playing=false;syncPlayButton();return}state.playing=true;speakCurrent(true)}
function stop(){speechSynthesis.cancel();state.playing=false;syncPlayButton()}
function next(){const c=DATA.chapters[state.chapter];if(state.segment<c.segments.length-1){state.segment++;updateCurrent();if(state.playing)speakCurrent(true);return}if(state.chapter<DATA.chapters.length-1)openChapter(state.chapter+1,0,state.playing)}
function prev(){if(state.segment>0){state.segment--;updateCurrent();if(state.playing)speakCurrent(true);return}if(state.chapter>0){const c=DATA.chapters[state.chapter-1];openChapter(state.chapter-1,c.segments.length-1,state.playing)}}
function syncPlayButton(){const b=$('#playBtn');b.textContent=speechSynthesis.paused?'▶ Devam':state.playing?'⏸ Duraklat':'▶ Dinle';b.classList.toggle('playing',state.playing)}
function setMode(m){state.mode=m;document.body.dataset.mode=m;$$('[data-mode]').forEach(b=>b.classList.toggle('on',b.dataset.mode===m));saveState()}
function init(){loadState();document.title=`${DATA.meta.title} · SpecBridge`;$('#brandTitle').textContent=DATA.meta.title;$('#brandSub').textContent=DATA.meta.subtitle;renderChapters();renderTranscript();renderSources();renderVisual();updateCurrent();setMode(state.mode);applyTheme();$('#playBtn').onclick=togglePlay;$('#stopBtn').onclick=stop;$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;$('#rate').value=String(state.rate);$('#rate').onchange=e=>{state.rate=+e.target.value;saveState();if(state.playing)speakCurrent(true)};$('#voiceSelect').onchange=e=>{state.voice=voices()[+e.target.value]||null;if(state.playing)speakCurrent(true)};$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));$('#autoNext').checked=state.autoNext;$('#autoNext').onchange=e=>state.autoNext=e.target.checked;$('#menuBtn').onclick=()=>document.body.classList.toggle('chapters-open');$('#transcriptBtn').onclick=()=>document.body.classList.toggle('transcript-open');$('#sourceBtn').onclick=()=>document.body.classList.toggle('sources-open');$('#closePanels').onclick=()=>document.body.classList.remove('chapters-open','transcript-open','sources-open');window.addEventListener('beforeunload',stop);speechSynthesis.onvoiceschanged=syncVoiceMenu;syncVoiceMenu();matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>{if(prefTheme()==='system')applyTheme('system')});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
