(()=>{
'use strict';
const DATA=window.DATACENTER_BRIEFING;if(!DATA)return;
const KEY='specbridge_datacenter_briefing_state',THEME_KEY='specbridge_project_theme';
const state={chapter:0,segment:0,playing:false,mode:'listen',rate:1,voice:null,autoNext:true,engine:'tts'};
const master=new Audio();master.preload='metadata';let masterChapter=-1;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const hasTTS=()=>('speechSynthesis'in window)&&('SpeechSynthesisUtterance'in window);
const synth=()=>hasTTS()?window.speechSynthesis:null;
function loadState(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');if(Number.isInteger(s.chapter))state.chapter=Math.max(0,Math.min(DATA.chapters.length-1,s.chapter));if(Number.isInteger(s.segment))state.segment=Math.max(0,s.segment);if(typeof s.rate==='number')state.rate=s.rate;if(s.mode)state.mode=s.mode}catch(_){}}
function saveState(){try{localStorage.setItem(KEY,JSON.stringify({chapter:state.chapter,segment:state.segment,rate:state.rate,mode:state.mode}))}catch(_){}}
function prefTheme(){try{const p=localStorage.getItem(THEME_KEY);return['light','dark','system'].includes(p)?p:'dark'}catch(_){return'dark'}}
function effectiveTheme(p=prefTheme()){if(p==='system')return matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';return p}
function applyTheme(p=prefTheme()){document.documentElement.dataset.theme=effectiveTheme(p);$$('[data-theme]').forEach(b=>b.classList.toggle('on',b.dataset.theme===p));let m=document.querySelector('meta[name="theme-color"]');if(m)m.content=effectiveTheme(p)==='dark'?'#061018':'#edf3f6'}
function setTheme(p){try{localStorage.setItem(THEME_KEY,p)}catch(_){}applyTheme(p)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function chapter(){return DATA.chapters[state.chapter]}
function mastered(c=chapter()){return !!(c?.audio&&Array.isArray(c.cues)&&c.cues.length)}
function cueForSegment(c=chapter(),seg=state.segment){return c?.cues?.find(x=>x.segment===seg)||c?.cues?.[seg]||null}
function segmentForTime(c,time){if(!c?.cues?.length)return state.segment;let found=c.cues[0].segment??0;for(const cue of c.cues){if(time>=cue.start)found=cue.segment??found;if(time>=cue.start&&time<(cue.end??Infinity))return cue.segment??found}return found}
function renderChapters(){const host=$('#chapterList');host.innerHTML=DATA.chapters.map((c,i)=>`<button class="chapter-item ${i===state.chapter?'active':''}" data-i="${i}"><span>${c.id}</span><div><b>${esc(c.title)}</b><small>${esc(c.kicker)} · ${c.segments.length} bölüm${mastered(c)?' · mastered audio':''}</small></div></button>`).join('');host.onclick=e=>{const b=e.target.closest('.chapter-item');if(!b)return;openChapter(+b.dataset.i,0,state.playing)};}
function renderTranscript(){const c=chapter(),host=$('#transcript');host.innerHTML=c.segments.map((s,i)=>`<button class="transcript-line ${i===state.segment?'active':''}" data-s="${i}"><span>${String(i+1).padStart(2,'0')}</span><p>${esc(s)}</p></button>`).join('');host.onclick=e=>{const b=e.target.closest('.transcript-line');if(!b)return;seekSegment(+b.dataset.s,state.playing)};}
function renderSources(){const c=chapter(),host=$('#sourceList');host.innerHTML=c.sources.map(k=>{const s=DATA.sources[k];return s?`<a class="source-card" href="${esc(s.url)}" target="_blank" rel="noopener"><span>OFFICIAL / PRIMARY SOURCE</span><b>${esc(s.name)}</b><strong>${esc(s.title)}</strong><p>${esc(s.note)}</p><em>Kaynağı aç ↗</em></a>`:''}).join('');}
function renderVisual(){const c=chapter(),v=$('#visual');const H={
 systems:`<div class="visual-title">DATA CENTER = SYSTEM OF SYSTEMS</div><div class="systems"><i>POWER</i><i>COOLING</i><i>NETWORK</i><i>SECURITY</i><i>OPERATIONS</i><b>IT CAPACITY</b></div><p>Kabinet yalnızca görünen son noktadır.</p>`,
 demand:`<div class="visual-title">GLOBAL CAPACITY DEMAND · SCENARIO</div><div class="bars"><div><b style="height:37%"></b><span>2025</span><strong>~82 GW</strong></div><div><b style="height:100%"></b><span>2030</span><strong>~220 GW</strong></div></div><p>McKinsey orta-senaryo büyüklükleri; tahmindir, garanti edilmiş talep değildir.</p>`,
 ai:`<div class="visual-title">AI CHANGES DENSITY</div><div class="density"><div><b>STANDARD IT</b><strong>Air / hybrid</strong><span>efficient general-purpose capacity</span></div><div class="hot"><b>AI / GPU</b><strong>High-density</strong><span>power · liquid/hybrid cooling · fabric</span></div></div>`,
 energy:`<div class="visual-title">DATA-CENTER ELECTRICITY DEMAND</div><div class="bars energy"><div><b style="height:51%"></b><span>2025</span><strong>~485 TWh</strong></div><div><b style="height:100%"></b><span>2030</span><strong>~950 TWh</strong></div></div><p>IEA central outlook context.</p>`,
 power:`<div class="visual-title">POWER CHAIN</div><div class="chain"><span>GRID / GEN</span><i>→</i><span>TRANSFORMER</span><i>→</i><span>SWITCHGEAR</span><i>→</i><span>UPS</span><i>→</i><span>DISTRIBUTION</span><i>→</i><b>RACK</b></div>`,
 cooling:`<div class="visual-title">THERMAL CHAIN</div><div class="chain"><span>CHIP</span><i>→</i><span>SERVER</span><i>→</i><span>RACK</span><i>→</i><span>ROOM</span><i>→</i><span>COOLING</span><i>→</i><b>HEAT REJECTION</b></div>`,
 network:`<div class="visual-title">INTERCONNECTION ECONOMY</div><div class="network-map"><b>DATA CENTER</b><span>Carrier A</span><span>Carrier B</span><span>IX</span><span>Cloud</span><span>DCI</span><span>OOB</span></div><p>Değer yalnız içerideki IT'den değil, bağlantı seçeneklerinden de gelir.</p>`,
 security:`<div class="visual-title">DEFENSE IN DEPTH</div><div class="rings"><div>PERIMETER<div>ACCESS<div>NETWORK<div>IDENTITY<div>DATA</div></div></div></div></div>`,
 operations:`<div class="visual-title">OPERATIONS LIFECYCLE</div><div class="loop"><span>MONITOR</span><i>→</i><span>OPERATE</span><i>→</i><span>MAINTAIN</span><i>→</i><span>CHANGE</span><i>→</i><span>LEARN</span></div><div class="ops-tags"><b>SOP</b><b>MOP</b><b>EOP</b><b>DCIM</b><b>BMS</b><b>EPMS</b></div>`,
 commissioning:`<div class="visual-title">INTEGRATED SYSTEMS TESTING</div><div class="test-grid"><span>UTILITY LOSS</span><span>UPS HOLD</span><span>GEN START</span><span>COOLING STABLE</span><span>NETWORK AVAILABLE</span><span>ALARMS CORRECT</span></div><strong class="center-note">The question is not “does each device work?” — it is “does the facility work together?”</strong>`,
 advisory:`<div class="visual-title">OWNER'S TECHNICAL GOVERNANCE</div><div class="advisory"><span>POWER VENDOR</span><span>COOLING VENDOR</span><span>NETWORK VENDOR</span><span>CONTRACTOR</span><b>INDEPENDENT ADVISER</b><strong>INVESTOR</strong></div><p>Danışman ürünün değil, yatırım kararının teknik temsilcisidir.</p>`,
 turkey:`<div class="visual-title">WHY TÜRKİYE?</div><div class="stats"><div><b>86M+</b><span>large domestic market</span></div><div><b>90%+</b><span>internet usage</span></div><div><b>IST</b><span>regional interconnection</span></div><div><b>AWS</b><span>Istanbul Local Zone</span></div><div><b>Google</b><span>Türkiye cloud region plan</span></div><div><b>AI/DC</b><span>policy & investment interest</span></div></div>`,
 whynow:`<div class="visual-title">WHY NOW?</div><div class="why-now"><span>GLOBAL COMPUTE DEMAND ↑</span><span>POWER SCARCITY IN MATURE HUBS</span><span>TÜRKİYE INTERCONNECTION ↑</span><span>HYPERSCALER SIGNALS ↑</span><b>PHASED OPPORTUNITY WINDOW</b></div>`,
 phases:`<div class="visual-title">PHASED CAPITAL DISCIPLINE</div><div class="phases"><span>MASTERPLAN</span><i>→</i><span>PHASE 1</span><i>→</i><span>ANCHOR / PRE-LEASE</span><i>→</i><span>EXPAND</span><i>→</i><b>SCALE</b></div><p>Nihai vizyon ile ilk gün CAPEX aynı olmak zorunda değildir.</p>`,
 closing:`<div class="visual-title">THE INVESTMENT EQUATION</div><div class="closing"><span>SECURED POWER</span><b>+</b><span>CONNECTIVITY</span><b>+</b><span>DEMAND</span><b>+</b><span>ENGINEERING</span><b>+</b><span>OPERATIONS</span></div><strong class="closing-line">= STRATEGIC DIGITAL INFRASTRUCTURE</strong>`
 };v.innerHTML=H[c.visual]||H.systems;}
function overallProgress(){const total=DATA.chapters.reduce((n,x)=>n+x.segments.length,0);let done=0;for(let i=0;i<state.chapter;i++)done+=DATA.chapters[i].segments.length;done+=state.segment;return Math.max(1,(done/Math.max(1,total-1))*100)}
function updateCurrent(){const c=chapter();state.segment=Math.max(0,Math.min(state.segment,c.segments.length-1));$('#chapterNo').textContent=`CHAPTER ${c.id}`;$('#chapterTitle').textContent=c.title;$('#chapterSummary').textContent=c.summary;$('#subtitle').textContent=c.segments[state.segment]||'';$('#progressText').textContent=`${state.chapter+1}/${DATA.chapters.length} · ${state.segment+1}/${c.segments.length}`;$('#progressFill').style.width=`${overallProgress()}%`;$$('.chapter-item').forEach((b,i)=>b.classList.toggle('active',i===state.chapter));$$('.transcript-line').forEach((b,i)=>b.classList.toggle('active',i===state.segment));$('.transcript-line.active')?.scrollIntoView({block:'nearest',behavior:'smooth'});saveState();}
function stopEngines(){synth()?.cancel();master.pause();state.playing=false;syncPlayButton()}
function prepareMaster(){const c=chapter();if(!mastered(c))return false;if(masterChapter!==state.chapter){master.pause();master.src=c.audio;masterChapter=state.chapter;master.load()}master.playbackRate=state.rate;return true}
function seekSegment(seg,play=false){const c=chapter();state.segment=Math.max(0,Math.min(c.segments.length-1,seg));if(mastered(c)){prepareMaster();const cue=cueForSegment(c,state.segment);if(cue)master.currentTime=Math.max(0,cue.start)}updateCurrent();if(play)playCurrent(true)}
function openChapter(i,s=0,play=false){stopEngines();state.chapter=Math.max(0,Math.min(DATA.chapters.length-1,i));state.segment=Math.max(0,s);renderChapters();renderTranscript();renderSources();renderVisual();updateCurrent();if(play)playCurrent(true)}
function voices(){return hasTTS()?synth().getVoices().filter(Boolean):[]}
function chooseVoice(){const vs=voices(),tr=vs.filter(v=>/^tr/i.test(v.lang));return tr.find(v=>/natural|neural|online|premium/i.test(v.name))||tr[0]||vs[0]||null}
function syncVoiceMenu(){const sel=$('#voiceSelect'),vs=voices();if(!vs.length){sel.innerHTML='<option>Browser TTS unavailable</option>';sel.disabled=true;return}sel.disabled=false;sel.innerHTML=vs.map((v,i)=>`<option value="${i}">${esc(v.name)} · ${esc(v.lang)}</option>`).join('');const wanted=chooseVoice(),idx=vs.indexOf(wanted);if(idx>=0)sel.value=String(idx);state.voice=wanted;}
function speakCurrent(restart=false){if(!hasTTS()){state.playing=false;syncPlayButton();$('#voiceStatus').textContent='Bu tarayıcı TTS desteklemiyor; mastered audio asset eklenebilir.';return}if(restart)synth().cancel();const c=chapter(),text=c.segments[state.segment];if(!text){state.playing=false;syncPlayButton();return}state.engine='tts';const u=new SpeechSynthesisUtterance(text);u.lang='tr-TR';u.rate=state.rate;u.pitch=.96;u.volume=1;if(state.voice)u.voice=state.voice;u.onstart=()=>{state.playing=true;syncPlayButton();updateCurrent();$('#voiceStatus').textContent='Browser TTS fallback · final mastered chapter audio tercih edilir.'};u.onend=()=>{if(!state.playing||state.engine!=='tts')return;if(state.segment<c.segments.length-1){state.segment++;speakCurrent(true)}else advanceChapter()};u.onerror=()=>{state.playing=false;syncPlayButton()};synth().speak(u)}
function playMaster(restart=false){const c=chapter();if(!prepareMaster())return false;state.engine='master';if(restart){const cue=cueForSegment(c,state.segment);if(cue)master.currentTime=Math.max(0,cue.start)}master.playbackRate=state.rate;master.play().then(()=>{state.playing=true;syncPlayButton();$('#voiceStatus').textContent='Mastered chapter audio · synchronized cue mode';}).catch(()=>{state.playing=false;syncPlayButton();});return true}
function playCurrent(restart=false){if(mastered())playMaster(restart);else speakCurrent(restart)}
function advanceChapter(){if(state.autoNext&&state.chapter<DATA.chapters.length-1){openChapter(state.chapter+1,0,true)}else{state.playing=false;syncPlayButton()}}
function togglePlay(){if(state.engine==='master'&&mastered()){if(!master.paused){master.pause();state.playing=false}else{playMaster(false)}syncPlayButton();return}if(hasTTS()&&synth().paused){synth().resume();state.playing=true;state.engine='tts';syncPlayButton();return}if(state.playing){if(state.engine==='tts'&&hasTTS())synth().pause();else master.pause();state.playing=false;syncPlayButton();return}playCurrent(false)}
function stop(){stopEngines();if(mastered()){const cue=cueForSegment();if(cue)master.currentTime=cue.start}}
function next(){const c=chapter();if(state.segment<c.segments.length-1){seekSegment(state.segment+1,state.playing);return}if(state.chapter<DATA.chapters.length-1)openChapter(state.chapter+1,0,state.playing)}
function prev(){if(state.segment>0){seekSegment(state.segment-1,state.playing);return}if(state.chapter>0){const c=DATA.chapters[state.chapter-1];openChapter(state.chapter-1,c.segments.length-1,state.playing)}}
function syncPlayButton(){const b=$('#playBtn');const paused=state.engine==='tts'&&hasTTS()&&synth().paused;b.textContent=paused?'▶ Devam':state.playing?'⏸ Duraklat':'▶ Dinle';b.classList.toggle('playing',state.playing)}
function setMode(m){state.mode=m;document.body.dataset.mode=m;$$('[data-mode]').forEach(b=>b.classList.toggle('on',b.dataset.mode===m));saveState()}
master.addEventListener('timeupdate',()=>{if(state.engine!=='master'||masterChapter!==state.chapter)return;const seg=segmentForTime(chapter(),master.currentTime);if(seg!==state.segment){state.segment=seg;updateCurrent()}const c=chapter(),cue=c.cues?.[c.cues.length-1],dur=Number.isFinite(master.duration)?master.duration:(cue?.end||1);const local=Math.min(100,(master.currentTime/Math.max(1,dur))*100);$('#voiceStatus').textContent=`Mastered audio · ${Math.floor(master.currentTime/60)}:${String(Math.floor(master.currentTime%60)).padStart(2,'0')} · chapter ${Math.round(local)}%`;});
master.addEventListener('ended',()=>{if(state.engine==='master')advanceChapter()});master.addEventListener('pause',()=>{if(state.engine==='master'&&!master.ended){state.playing=false;syncPlayButton()}});
function init(){loadState();document.title=`${DATA.meta.title} · SpecBridge`;$('#brandTitle').textContent=DATA.meta.title;$('#brandSub').textContent=DATA.meta.subtitle;renderChapters();renderTranscript();renderSources();renderVisual();updateCurrent();setMode(state.mode);applyTheme();$('#playBtn').onclick=togglePlay;$('#stopBtn').onclick=stop;$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;$('#rate').value=String(state.rate);$('#rate').onchange=e=>{state.rate=+e.target.value;master.playbackRate=state.rate;saveState();if(state.playing&&state.engine==='tts')speakCurrent(true)};$('#voiceSelect').onchange=e=>{state.voice=voices()[+e.target.value]||null;if(state.playing&&state.engine==='tts')speakCurrent(true)};$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));$('#autoNext').checked=state.autoNext;$('#autoNext').onchange=e=>state.autoNext=e.target.checked;$('#menuBtn').onclick=()=>document.body.classList.toggle('chapters-open');$('#transcriptBtn').onclick=()=>document.body.classList.toggle('transcript-open');$('#sourceBtn').onclick=()=>document.body.classList.toggle('sources-open');$('#closePanels').onclick=()=>document.body.classList.remove('chapters-open','transcript-open','sources-open');window.addEventListener('beforeunload',stopEngines);if(hasTTS()){synth().onvoiceschanged=syncVoiceMenu;syncVoiceMenu()}else syncVoiceMenu();matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>{if(prefTheme()==='system')applyTheme('system')});$('#voiceStatus').textContent=mastered()?'Mastered chapter audio ready':'Professional audio-ready · browser TTS fallback';}
window.SPECBRIDGE_BRIEFING={openChapter,seekSegment,play:()=>playCurrent(false),stop,setMode,setTheme,getState:()=>({...state})};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
