(function(){
'use strict';
const DV={
T00:'މި ޓޮޕޮލޮޖީ މެޕަކީ Haven Healthcare ގެ މައިގަނޑު ނެވިގޭޝަން ލޭޔަރެވެ. އެގްޒެކެޓިވް އާކިޓެކްޗަރ، ލޮޖިކަލް ނެޓްވޯކް، ފިޒިކަލް ކަނެކްޓިވިޓީ، ޕްރައިވެޓް ކްލައުޑް، އޮޕަރޭޝަންސް، ހެލްތްކެއަރ ސަރވިސަސް، ސެކިއުރިޓީ އަދި ރިކަވަރީ އެއް ޑިޖިޓަލް ހޮސްޕިޓަލް މޮޑެލެއްގައި ގުޅާލެވެއެވެ.',
T01:'Haven Healthcare އަކީ އެއް އެކުވެރި ޑިޖިޓަލް ހޮސްޕިޓަލް ޕްލެޓްފޯމެއް ގޮތަށް ޑިޒައިން ކުރެވިފައިވާ ސިސްޓަމެކެވެ. ރެޒިލިއަންޓް campus backbone އިން ކްލިނިކަލް ޔޫޒަރުން އަދި wireless mobility ސަޕޯޓް ކުރެއެވެ.',
T02:'ލޮޖިކަލް އާކިޓެކްޗަރުން clinical، imaging، medical IoT، staff، guest، BMS، nurse call، CCTV، access control އަދި corporate services ވަކިވަކިން ސެގްމެންޓް ކުރެއެވެ.',
T03:'ފިޒިކަލް މޮޑެލުން ތަސްދީޤު ކުރެވިފައިވާ މަތީ ދަރަޖައިގެ ކަނެކްޓިވިޓީ ދައްކައެވެ. Data-center fabric އިން campus core އަށް redundant 100G ޕާތްތައް ހުރެއެވެ.',
T04:'ހޮސްޕިޓަލް IT ޕްލެޓްފޯމް 4-node private cloud، ވަކި PACS storage އަދި independent backup tier މައްޗަށް ބިނާކުރެވިފައިވެއެވެ.',
T05:'އޮޕަރޭޝަން މެނޭޖްމަންޓް dedicated out-of-band network އަކުން production traffic އިން ވަކިކުރެވެއެވެ.',
T06:'Healthcare services ކްލިނިކަލް އަދި އޮޕަރޭޝަނަލް ރޯލްތަކަށް ބަލައި އޮރގަނައިޒް ކުރެވެއެވެ.',
T07:'Security ބިނާކުރެވިފައިވަނީ layered protection މައްޗަށެވެ: redundant perimeter، segmented internal services އަދި centralized identity controls.',
T08:'Recovery model ގައި production، backup އަދި future disaster recovery ވަކިކުރެވެއެވެ.'};
let lang='en';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function viewId(){const b=$('#tabs button.on');return b?(b.dataset.v||((b.textContent.match(/T0[0-8]/)||['T00'])[0])):'T00'}
function originalLang(){const b=$('#langBtn');return b?b.textContent.trim().toLowerCase():'en'}
function setOriginalLang(target){const b=$('#langBtn');if(!b)return; if(target==='dv')target='en';let guard=0;while(originalLang()!==target&&guard++<3)b.click()}
function narrative(v){if(lang==='dv')return DV[v]||DV.T00;if(v==='T00')return lang==='tr'?'Bu topoloji haritası Haven Healthcare için ana navigasyon katmanıdır. Executive architecture, mantıksal network, fiziksel bağlantı, private cloud, operasyon, healthcare services, security ve recovery görünümlerini tek bir yatırımcı odaklı dijital hastane modeli altında birleştirir.':'This topology map is the navigation layer for Haven Healthcare. It connects the executive architecture, logical network, physical connectivity, private cloud, operations, healthcare services, security and recovery views into one investor-oriented digital hospital model.';const a=window.HT&&window.HT.a&&window.HT.a[v];return a?(a[lang]||a.en):($('#narrativeText')?.textContent||'')}
function bestVoice(code){const pref=code.slice(0,2).toLowerCase();const score=v=>{const n=(v.name||'').toLowerCase(),l=(v.lang||'').toLowerCase();let s=l===code.toLowerCase()?50:l.startsWith(pref)?35:0;if(n.includes('natural'))s+=20;if(n.includes('neural'))s+=18;if(n.includes('online'))s+=14;if(n.includes('google'))s+=10;if(n.includes('microsoft'))s+=8;return s};return speechSynthesis.getVoices().filter(v=>(v.lang||'').toLowerCase().startsWith(pref)).sort((a,b)=>score(b)-score(a))[0]||null}
function speak(){const code=lang==='tr'?'tr-TR':lang==='dv'?'dv-MV':'en-US';const u=new SpeechSynthesisUtterance(narrative(viewId()));u.lang=code;u.rate=lang==='tr'?0.92:0.94;const v=bestVoice(code);if(v)u.voice=v;speechSynthesis.cancel();speechSynthesis.speak(u)}
function patchImage(){const fresh='assets/haven-proposed-completion.jpg?v=20260831-1218';$$('image').filter(x=>(x.getAttribute('href')||'').includes('haven-proposed-completion')).forEach(img=>{img.setAttribute('href',fresh);img.setAttributeNS('http://www.w3.org/1999/xlink','href',fresh)});$$('a.vision-link').forEach(a=>{if((a.getAttribute('href')||'').includes('haven-proposed-completion'))a.setAttribute('href',fresh)})}
function apply(){setTimeout(()=>{const v=viewId(),n=$('#narrativeText');if(n){n.textContent=narrative(v);n.dir=lang==='dv'?'rtl':'ltr';n.style.textAlign=lang==='dv'?'right':'left'}patchImage()},0)}
function installHeader(){const actions=$('.actions');if(!actions)return;const old=$('#langBtn');if(old)old.style.display='none';let wrap=$('#hvLangWrap');if(!wrap){wrap=document.createElement('div');wrap.id='hvLangWrap';wrap.innerHTML='<button id="hvLangBtn" type="button">EN ▾</button><div id="hvLangMenu"><button data-hvl="en">English</button><button data-hvl="tr">Türkçe</button><button data-hvl="dv" dir="rtl">ދިވެހި · Dhivehi</button></div>';const print=$('.print-wrap');actions.insertBefore(wrap,print||null);$('#hvLangBtn').onclick=e=>{e.stopPropagation();$('#hvLangMenu').classList.toggle('open')};$$('[data-hvl]').forEach(b=>b.onclick=e=>{e.stopPropagation();lang=b.dataset.hvl;setOriginalLang(lang);$('#hvLangBtn').textContent=lang==='dv'?'DV ▾':lang.toUpperCase()+' ▾';$('#hvLangMenu').classList.remove('open');apply()});document.addEventListener('click',()=>$('#hvLangMenu')?.classList.remove('open'))}
}
function ensurePrint(){const deck=$('#printDeck');if(!deck||deck.innerHTML.trim())return;const svg=$('#topologySvg');if(!svg)return;const v=viewId();deck.innerHTML='<section class="print-page"><div class="hvWm">specbridge.co - confidential</div><h1>Haven Healthcare · '+v+'</h1><div class="psub">Digital Infrastructure Review</div>'+svg.cloneNode(true).outerHTML+'<div class="print-footer"><span>Önder Yardaş</span><span>specbridge.co · Confidential</span></div></section>'}
function install(){const st=document.createElement('style');st.id='hv047';st.textContent=`header{display:flex!important;gap:8px!important;padding:0 12px!important}.brand{width:215px!important;flex:0 0 215px!important}#tabs{flex:1 1 auto!important;min-width:0!important;overflow-x:auto!important}.actions{display:flex!important;position:static!important;flex:0 0 auto!important;align-items:center!important;gap:5px!important;max-width:none!important;padding:0!important}.actions>button,.actions .print-wrap button,#hvLangBtn{font-size:8px!important;padding:6px 7px!important;white-space:nowrap!important}.print-wrap{position:relative!important;top:auto!important;right:auto!important;z-index:200!important;display:block!important}#hvLangWrap{position:relative!important;display:block!important;flex:0 0 auto!important}#hvLangBtn{border:1px solid #ffffff40;background:#ffffff0d;color:#fff;border-radius:7px;cursor:pointer;min-width:48px}#hvLangMenu{display:none;position:absolute;right:0;top:34px;width:145px;background:#fff;border:1px solid #cbd9e3;border-radius:8px;box-shadow:0 12px 30px #0003;padding:5px;z-index:1500}#hvLangMenu.open{display:block}#hvLangMenu button{display:block;width:100%;text-align:left;border:0;background:#fff;color:#17324a;padding:8px;border-radius:6px;cursor:pointer}#hvLangMenu button[dir=rtl]{text-align:right}.print-menu{right:0!important;top:34px!important;z-index:1600!important}@media(max-width:1380px){.brand{width:185px!important;flex-basis:185px!important}#tabs button,.actions>button,.actions .print-wrap button,#hvLangBtn{font-size:7.2px!important;padding:5px!important}}@media print{.print-page::before{content:none!important}.hvWm{display:block!important;position:absolute!important;left:50%!important;top:48%!important;transform:translate(-50%,-50%) rotate(-28deg)!important;font-size:34pt!important;font-weight:800!important;letter-spacing:.08em!important;color:rgba(16,54,80,.13)!important;z-index:10!important;white-space:nowrap!important}.print-page svg{position:relative!important;z-index:1!important}.print-footer,.print-page h1,.print-page .psub{position:relative!important;z-index:11!important}}`;document.head.appendChild(st);installHeader();['voiceBtn','playBtn'].forEach(id=>{const b=document.getElementById(id);if(b){const n=b.cloneNode(true);b.replaceWith(n);n.addEventListener('click',speak)}});$('#tabs')?.addEventListener('click',apply);$('#topologySvg')?.addEventListener('click',apply);window.addEventListener('beforeprint',ensurePrint);new MutationObserver(patchImage).observe($('#topologySvg'),{childList:true,subtree:true});apply()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();