(function(){
  'use strict';
  const DV = {
    T00: 'މި ޓޮޕޮލޮޖީ މެޕަކީ Haven Healthcare ގެ މައިގަނޑު ނެވިގޭޝަން ލޭޔަރެވެ. އެގްޒެކެޓިވް އާކިޓެކްޗަރ، ލޮޖިކަލް ނެޓްވޯކް، ފިޒިކަލް ކަނެކްޓިވިޓީ، ޕްރައިވެޓް ކްލައުޑް، އޮޕަރޭޝަންސް، ހެލްތްކެއަރ ސަރވިސަސް، ސެކިއުރިޓީ އަދި ރިކަވަރީ އެއް ޑިޖިޓަލް ހޮސްޕިޓަލް މޮޑެލެއްގައި ގުޅާލެވެއެވެ.',
    T01: 'Haven Healthcare ޑިޒައިން ކުރެވިފައިވަނީ އެއް އެކުވެރި ޑިޖިޓަލް ހޮސްޕިޓަލް ޕްލެޓްފޯމެއް ގޮތަށެވެ. ރެޒިލިއަންޓް campus backbone އިން ކްލިނިކަލް ޔޫޒަރުން އަދި wireless mobility ސަޕޯޓް ކުރާއިރު، ވަކި high-speed data-center fabric އަކުން private cloud، PACS storage އަދި backup ގުޅާލެވެއެވެ. މަޤްޞަދަކީ continuity، clinical data protection އަދި controlled growth އެވެ.',
    T02: 'ލޮޖިކަލް އާކިޓެކްޗަރުން clinical، imaging، medical IoT، staff، guest، BMS، nurse call، CCTV، access control އަދި corporate services ވަކިވަކިން ސެގްމެންޓް ކުރެއެވެ. މިއީ ނުބޭނުން ކޮމިއުނިކޭޝަން މަދުކޮށް ކޮންމެ ސަރވިސް ރޯލަކަށް އެއްގޮތް security policy އެޅުމަށް އެހީވެދެއެވެ.',
    T03: 'ފިޒިކަލް މޮޑެލުން ދައްކަނީ ތަސްދީޤު ކުރެވިފައިވާ މަތީ ދަރަޖައިގެ ކަނެކްޓިވިޓީ އެކަންޏެވެ. Data-center fabric އިން campus core އަށް redundant 100G ޕާތްތައް ހުރުމާއި، HCI އަދި PACS storage އިން dedicated 25G ލިންކްތައް ބޭނުން ކުރެއެވެ. ފްލޯރުތަކުގެ ތަފްސީލީ ކޭބަލިންގ އެންޖިނިއަރިންގ ސަރވޭގައި ފައިނަލް ކުރެވޭނެއެވެ.',
    T04: 'ހޮސްޕިޓަލް IT ޕްލެޓްފޯމް ބިނާކުރެވިފައިވަނީ 4-node private cloud، ވަކި PACS storage އަދި independent backup tier އެއް މައްޗަށެވެ. މި ވަކިކުރުމުން clinical imaging data ބޮޑުވެފައި ޖެނެރަލް application capacity ކުޑަނުވެ އަދި ރިކަވަރީ މޮޑެލް ސާފުވެއެވެ.',
    T05: 'އޮޕަރޭޝަން މެނޭޖްމަންޓް dedicated out-of-band network އަކުން production traffic އިން ވަކިކުރެވެއެވެ. U-Center އަދި campus management ފަންކްޝަންތަކުން centralized visibility، identity އަދި operational control އަށް ބިންގާ ޤާއިމް ކުރެއެވެ.',
    T06: 'Healthcare services ކްލިނިކަލް އަދި އޮޕަރޭޝަނަލް ރޯލްތަކަށް ބަލައި އޮރގަނައިޒް ކުރެވެއެވެ. Imaging، medical devices، nurse call، security، building systems، corporate users އަދި guest services އެއް resilient physical infrastructure ބޭނުން ކުރާއިރު ލޮޖިކަލް ގޮތުން ވަކިކުރެވެއެވެ.',
    T07: 'Security ބިނާކުރެވިފައިވަނީ layered protection މައްޗަށެވެ: redundant perimeter، segmented internal services އަދި centralized identity controls. ފައިނަލް firewall އަދި access-control rules ހޮސްޕިޓަލް application އަދި medical-device vendors އެކު ނިންމާލެވޭނެއެވެ.',
    T08: 'Recovery model ގައި production، backup އަދި future disaster recovery ވަކިކުރެވެއެވެ. Backup tier ބޭސްލައިންގެ ބައެއް ކަމަށްވާއިރު off-site DR target، replication design އަދި RPO/RTO ފައިނަލް ޑިޒައިން ފޭސްގައި ތަސްދީޤު ކުރެވޭނެއެވެ.'
  };
  const TR_TITLES = {T00:'Topoloji Haritası',T01:'Yönetici Mimarisi',T02:'Mantıksal Ağ',T03:'Fiziksel Bağlantı',T04:'Compute / HCI / Storage',T05:'Yönetim / OOB',T06:'Sağlık Hizmetleri',T07:'Güvenlik',T08:'Yedekleme / DR'};
  const DV_TITLES = {T00:'ޓޮޕޮލޮޖީ މެޕް',T01:'އެގްޒެކެޓިވް އާކިޓެކްޗަރ',T02:'ލޮޖިކަލް ނެޓްވޯކް',T03:'ފިޒިކަލް ކަނެކްޓިވިޓީ',T04:'Compute / HCI / Storage',T05:'މެނޭޖްމަންޓް / OOB',T06:'ހެލްތްކެއަރ ސަރވިސަސް',T07:'ސެކިއުރިޓީ',T08:'ބެކަޕް / DR'};
  let language='en';
  function currentViewId(){ const on=document.querySelector('#tabs button.on'); if(!on)return'T00'; return on.dataset.v||((on.textContent.match(/T0[0-8]/)||['T00'])[0]); }
  function getNarrative(view){ if(language==='dv')return DV[view]||DV.T00; if(view==='T00')return language==='tr'?'Bu topoloji haritası Haven Healthcare için ana navigasyon katmanıdır. Executive architecture, mantıksal network, fiziksel bağlantı, private cloud, operasyon, healthcare services, security ve recovery görünümlerini tek bir yatırımcı odaklı dijital hastane modeli altında birleştirir.':'This topology map is the navigation layer for Haven Healthcare. It connects the executive architecture, logical network, physical connectivity, private cloud, operations, healthcare services, security and recovery views into one investor-oriented digital hospital model.'; const a=window.HT&&window.HT.a&&window.HT.a[view]; return a?(a[language]||a.en):document.getElementById('narrativeText').textContent; }
  function getTitle(view){ if(language==='tr')return TR_TITLES[view]||view; if(language==='dv')return DV_TITLES[view]||view; if(view==='T00')return'Topology Map'; return window.HT&&window.HT.v&&window.HT.v[view]?window.HT.v[view][0]:view; }
  function labels(){ if(language==='tr')return{narr:'YATIRIMCI ANLATIMI',final:'FİNAL TASARIM KONULARI',play:'▶ Dinlet',voice:'▶ Seslendirme'}; if(language==='dv')return{narr:'އިންވެސްޓަރ ނެރޭޝަން',final:'ފައިނަލް ޑިޒައިން އައިޓަމްސް',play:'▶ އަޑު އިއްވާ',voice:'▶ ނެރޭޝަން'}; return{narr:'INVESTOR NARRATIVE',final:'FINAL DESIGN ITEMS',play:'▶ Play',voice:'▶ Narration'}; }
  function applyLanguage(){ const view=currentViewId(),nar=document.getElementById('narrativeText'); if(nar){nar.textContent=getNarrative(view);nar.dir=language==='dv'?'rtl':'ltr';nar.style.textAlign=language==='dv'?'right':'left';} const vt=document.getElementById('viewTitle');if(vt)vt.textContent=getTitle(view); const caps=document.querySelectorAll('.left .cap'),l=labels();if(caps[0])caps[0].textContent=l.narr;if(caps[1])caps[1].textContent=l.final;const p=document.getElementById('playBtn');if(p)p.textContent=l.play;const v=document.getElementById('voiceBtn');if(v)v.textContent=l.voice;const lb=document.getElementById('hvLangBtn');if(lb)lb.textContent=language==='dv'?'DV · ދިވެހި ▾':language.toUpperCase()+' ▾';document.documentElement.lang=language==='dv'?'dv':language; }
  function scoreVoice(v,lang){let s=0,name=(v.name||'').toLowerCase(),vl=(v.lang||'').toLowerCase();if(vl===lang.toLowerCase())s+=50;else if(vl.startsWith(lang.slice(0,2).toLowerCase()))s+=35;if(name.includes('natural'))s+=18;if(name.includes('neural'))s+=16;if(name.includes('online'))s+=12;if(name.includes('google'))s+=10;if(name.includes('microsoft'))s+=8;return s;}
  function bestVoice(lang){return speechSynthesis.getVoices().filter(v=>v.lang&&v.lang.toLowerCase().startsWith(lang.slice(0,2).toLowerCase())).sort((a,b)=>scoreVoice(b,lang)-scoreVoice(a,lang))[0]||null;}
  function toast(msg){let t=document.getElementById('hvToast');if(!t){t=document.createElement('div');t.id='hvToast';document.body.appendChild(t);}t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),3500);}
  function speakCurrent(){const view=currentViewId(),text=getNarrative(view),lang=language==='tr'?'tr-TR':language==='dv'?'dv-MV':'en-US';speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=language==='tr'?0.92:0.94;u.pitch=1;const voice=bestVoice(lang);if(voice){u.voice=voice;toast((language==='tr'?'Türkçe ses: ':language==='dv'?'Dhivehi voice: ':'Voice: ')+voice.name);}else if(language==='dv'){toast('Dhivehi (dv-MV) voice is not installed in this browser; text mode remains available.');}speechSynthesis.speak(u);}
  function installVoiceControls(){['voiceBtn','playBtn'].forEach(id=>{const old=document.getElementById(id);if(!old)return;const n=old.cloneNode(true);old.replaceWith(n);n.addEventListener('click',speakCurrent);});}
  function installLanguageMenu(){const old=document.getElementById('langBtn');if(!old)return;const wrap=document.createElement('div');wrap.className='hv-lang-wrap';wrap.innerHTML='<button id="hvLangBtn" type="button">EN ▾</button><div id="hvLangMenu" class="hv-lang-menu"><button data-lang="en">English</button><button data-lang="tr">Türkçe</button><button data-lang="dv" dir="rtl">ދިވެހި · Dhivehi</button></div>';old.replaceWith(wrap);const btn=wrap.querySelector('#hvLangBtn'),menu=wrap.querySelector('#hvLangMenu');btn.addEventListener('click',e=>{e.stopPropagation();menu.classList.toggle('open')});menu.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();language=b.dataset.lang;menu.classList.remove('open');applyLanguage();}));document.addEventListener('click',()=>menu.classList.remove('open'));}
  function ensurePrintDeck(){const deck=document.getElementById('printDeck');if(!deck)return;if(!deck.innerHTML.trim()){const view=currentViewId(),title=getTitle(view),svg=document.getElementById('topologySvg');if(!svg)return;const copy=svg.cloneNode(true);copy.removeAttribute('id');deck.dataset.hvAuto='1';deck.innerHTML='<section class="print-page"><div class="hv-watermark">specbridge.co - confidential</div><h1>Haven Healthcare · '+view+' · '+title+'</h1><div class="psub">'+(document.getElementById('viewSubtitle')?.textContent||'Digital Infrastructure Review')+'</div>'+copy.outerHTML+'<div class="print-footer"><span>Önder Yardaş</span><span>specbridge.co · Confidential</span></div></section>';}deck.querySelectorAll('.print-page').forEach(p=>{if(!p.querySelector('.hv-watermark')){const w=document.createElement('div');w.className='hv-watermark';w.textContent='specbridge.co - confidential';p.prepend(w);}});}
  function installPrintFix(){window.addEventListener('beforeprint',ensurePrintDeck);window.addEventListener('afterprint',()=>{const d=document.getElementById('printDeck');if(d&&d.dataset.hvAuto==='1'){d.innerHTML='';delete d.dataset.hvAuto;}});}
  function installStyles(){const s=document.createElement('style');s.textContent='header{padding-right:104px!important}.print-wrap{position:fixed!important;top:14px!important;right:12px!important;z-index:1200!important}.print-wrap>#printBtn{background:#fff!important;color:#103650!important;border-color:#fff!important;font-weight:800!important}.print-menu{right:0!important;top:36px!important;z-index:1300!important}.hv-lang-wrap{position:relative;display:inline-block}.hv-lang-wrap>button{border:1px solid #ffffff40;background:#ffffff0d;color:#fff;border-radius:7px;padding:7px 8px;font-size:9px;cursor:pointer;white-space:nowrap}.hv-lang-menu{display:none;position:absolute;right:0;top:36px;width:145px;background:#fff;border:1px solid #cbd9e3;border-radius:8px;box-shadow:0 12px 30px #0002;padding:5px;z-index:1400}.hv-lang-menu.open{display:block}.hv-lang-menu button{display:block;width:100%;text-align:left;border:0;background:#fff;color:#17324a;padding:8px;border-radius:6px;cursor:pointer}.hv-lang-menu button:hover{background:#eef5f9}.hv-lang-menu button[dir=rtl]{text-align:right;font-family:"Noto Sans Thaana","Segoe UI",Arial,sans-serif}#hvToast{position:fixed;right:14px;bottom:14px;z-index:5000;background:#103650;color:white;padding:9px 12px;border-radius:8px;font:10px Segoe UI,Arial,sans-serif;opacity:0;transform:translateY(8px);pointer-events:none;transition:.2s}#hvToast.show{opacity:1;transform:none}.hv-watermark{display:none}@media(max-width:1380px){.brand{width:205px!important}#tabs button,.actions button,.hv-lang-wrap>button{padding:6px 6px!important;font-size:8px!important}}@media print{.print-page::before{content:none!important}.hv-watermark{display:block!important;position:absolute!important;left:50%!important;top:49%!important;transform:translate(-50%,-50%) rotate(-28deg)!important;font-size:34pt!important;font-weight:800!important;letter-spacing:.08em!important;color:rgba(16,54,80,.14)!important;white-space:nowrap!important;z-index:10!important;pointer-events:none!important}.print-page svg{z-index:1!important}.print-footer,.print-page h1,.print-page .psub{position:relative!important;z-index:11!important}}';document.head.appendChild(s);}
  function init(){installStyles();installLanguageMenu();installVoiceControls();installPrintFix();applyLanguage();document.getElementById('tabs')?.addEventListener('click',()=>setTimeout(applyLanguage,0));document.getElementById('topologySvg')?.addEventListener('click',()=>setTimeout(applyLanguage,0));}
  if(document.readyState==='complete')init();else window.addEventListener('load',init,{once:true});
})();