(function(){
'use strict';
if(window.__HAVEN_STABILIZER_V050__) return;
window.__HAVEN_STABILIZER_V050__=true;
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const DV={
T00:'މި ޓޮޕޮލޮޖީ މެޕަކީ Haven Healthcare ގެ މައިގަނޑު ނެވިގޭޝަން ލޭޔަރެވެ. އެގްޒެކެޓިވް އާކިޓެކްޗަރ، ލޮޖިކަލް ނެޓްވޯކް، ފިޒިކަލް ކަނެކްޓިވިޓީ، ޕްރައިވެޓް ކްލައުޑް، އޮޕަރޭޝަންސް، ހެލްތްކެއަރ ސަރވިސަސް، ސެކިއުރިޓީ އަދި ރިކަވަރީ އެއް ޑިޖިޓަލް ހޮސްޕިޓަލް މޮޑެލެއްގައި ގުޅާލެވެއެވެ.',
T01:'Haven Healthcare އަކީ އެއް އެކުވެރި ޑިޖިޓަލް ހޮސްޕިޓަލް ޕްލެޓްފޯމެކެވެ. ރެޒިލިއަންޓް campus backbone އިން clinical users އަދި wireless mobility ސަޕޯޓް ކުރެއެވެ.',
T02:'ލޮޖިކަލް އާކިޓެކްޗަރުން clinical، imaging، medical IoT، staff، guest، BMS، nurse call، CCTV، access control އަދި corporate services ވަކިވަކިން ސެގްމެންޓް ކުރެއެވެ.',
T03:'ފިޒިކަލް މޮޑެލުން ތަސްދީޤު ކުރެވިފައިވާ މަތީ ދަރަޖައިގެ ކަނެކްޓިވިޓީ ދައްކައެވެ. Data-center fabric އިން campus core އަށް redundant 100G ޕާތްތައް ހުރެއެވެ.',
T04:'ހޮސްޕިޓަލް IT ޕްލެޓްފޯމް 4-node private cloud، PACS storage އަދި independent backup tier މައްޗަށް ބިނާކުރެވިފައިވެއެވެ.',
T05:'އޮޕަރޭޝަން މެނޭޖްމަންޓް dedicated out-of-band network އަކުން production traffic އިން ވަކިކުރެވެއެވެ.',
T06:'Healthcare services ކްލިނިކަލް އަދި އޮޕަރޭޝަނަލް ރޯލްތަކަށް ބަލައި އޮރގަނައިޒް ކުރެވެއެވެ.',
T07:'Security ބިނާކުރެވިފައިވަނީ layered protection މައްޗަށެވެ: redundant perimeter، segmented internal services އަދި centralized identity controls.',
T08:'Recovery model ގައި production، backup އަދި future disaster recovery ވަކިކުރެވެއެވެ.'};
const TR_T={T00:'Topoloji Haritası',T01:'Yönetici Mimarisi',T02:'Mantıksal Ağ',T03:'Fiziksel Bağlantı',T04:'Compute / HCI / Storage',T05:'Yönetim / OOB',T06:'Sağlık Hizmetleri',T07:'Güvenlik',T08:'Yedekleme / DR'};
const DV_T={T00:'ޓޮޕޮލޮޖީ މެޕް',T01:'އެގްޒެކެޓިވް އާކިޓެކްޗަރ',T02:'ލޮޖިކަލް ނެޓްވޯކް',T03:'ފިޒިކަލް ކަނެކްޓިވިޓީ',T04:'Compute / HCI / Storage',T05:'މެނޭޖްމަންޓް / OOB',T06:'ހެލްތްކެއަރ ސަރވިސަސް',T07:'ސެކިއުރިޓީ',T08:'ބެކަޕް / DR'};
let lang='en';
function vid(){const b=$('#tabs button.on');return b?(b.dataset.v||((b.textContent.match(/T0[0-8]/)||['T00'])[0])):'T00';}
function narrative(v){if(lang==='dv')return DV[v]||DV.T00;if(v==='T00')return lang==='tr'?'Bu topoloji haritası Haven Healthcare için ana navigasyon katmanıdır. Yönetici mimarisi, mantıksal ağ, fiziksel bağlantı, private cloud, operasyon, sağlık servisleri, güvenlik ve geri dönüş görünümlerini tek bir yatırımcı odaklı dijital hastane modeli altında birleştirir.':'This topology map is the navigation layer for Haven Healthcare. It connects the executive architecture, logical network, physical connectivity, private cloud, operations, healthcare services, security and recovery views into one investor-oriented digital hospital model.';const a=window.HT&&window.HT.a&&window.HT.a[v];return a?(a[lang]||a.en):($('#narrativeText')?.textContent||'');}
function title(v){if(lang==='tr')return TR_T[v]||v;if(lang==='dv')return DV_T[v]||v;if(v==='T00')return'Topology Map';return window.HT&&window.HT.v&&window.HT.v[v]?window.HT.v[v][0]:v;}
function bestVoice(code){const p=code.slice(0,2).toLowerCase();const score=v=>{const n=(v.name||'').toLowerCase(),l=(v.lang||'').toLowerCase();let s=l===code.toLowerCase()?60:l.startsWith(p)?40:0;if(n.includes('natural'))s+=25;if(n.includes('neural'))s+=22;if(n.includes('online'))s+=15;if(n.includes('google'))s+=10;if(n.includes('microsoft'))s+=8;return s;};return speechSynthesis.getVoices().filter(v=>(v.lang||'').toLowerCase().startsWith(p)).sort((a,b)=>score(b)-score(a))[0]||null;}
function speak(){const code=lang==='tr'?'tr-TR':lang==='dv'?'dv-MV':'en-US';const u=new SpeechSynthesisUtterance(narrative(vid()));u.lang=code;u.rate=lang==='tr'?0.92:0.94;const v=bestVoice(code);if(v)u.voice=v;speechSynthesis.cancel();speechSynthesis.speak(u);}
function patchImage(){const u='assets/haven-proposed-completion.jpg?v=20260831-1230';$$('image').filter(i=>(i.getAttribute('href')||'').includes('haven-proposed-completion')).forEach(i=>{i.setAttribute('href',u);i.setAttributeNS('http://www.w3.org/1999/xlink','href',u);});$$('a.vision-link').forEach(a=>{if((a.getAttribute('href')||'').includes('haven-proposed-completion'))a.href=u;});}
function applyLanguage(){const v=vid(),n=$('#narrativeText');if(n){n.textContent=narrative(v);n.dir=lang==='dv'?'rtl':'ltr';n.style.textAlign=lang==='dv'?'right':'left';}const vt=$('#viewTitle');if(vt)vt.textContent=title(v);const caps=$$('.left .cap');if(caps[0])caps[0].textContent=lang==='tr'?'YATIRIMCI ANLATIMI':lang==='dv'?'އިންވެސްޓަރ ނެރޭޝަން':'INVESTOR NARRATIVE';if(caps[1])caps[1].textContent=lang==='tr'?'FİNAL TASARIM KONULARI':lang==='dv'?'ފައިނަލް ޑިޒައިން އައިޓަމްސް':'FINAL DESIGN ITEMS';patchImage();}
function cleanHeader(){
  $$('.hv-lang-wrap,#hvLangWrap,#hvHeaderFixV046').forEach(e=>e.remove());
  const old=$('#langBtn');if(old)old.style.display='none';
  const actions=$('.actions'),print=$('.print-wrap');if(!actions)return;
  const sel=document.createElement('select');sel.id='hvLangSelect';sel.title='Language / Dil / ބަސް';sel.innerHTML='<option value="en">EN</option><option value="tr">TR</option><option value="dv">DV</option>';sel.value=lang;sel.addEventListener('change',()=>{lang=sel.value;applyLanguage();});actions.insertBefore(sel,print||null);
  ['voiceBtn','playBtn'].forEach(id=>{const b=document.getElementById(id);if(!b)return;const n=b.cloneNode(true);b.replaceWith(n);n.addEventListener('click',speak);});
}
function ensurePrint(){const d=$('#printDeck');if(!d)return;if(!d.innerHTML.trim()){const svg=$('#topologySvg');if(!svg)return;d.dataset.auto='1';d.innerHTML='<section class="print-page"><div class="hvWM">specbridge.co - confidential</div><h1>Haven Healthcare · '+vid()+' · '+title(vid())+'</h1><div class="psub">Digital Infrastructure Review</div>'+svg.cloneNode(true).outerHTML+'<div class="print-footer"><span>Önder Yardaş</span><span>specbridge.co · Confidential</span></div></section>';}$$('#printDeck .print-page').forEach(p=>{if(!p.querySelector('.hvWM')){const w=document.createElement('div');w.className='hvWM';w.textContent='specbridge.co - confidential';p.prepend(w);}});}
function styles(){const s=document.createElement('style');s.id='havenStable050';s.textContent=`header{display:grid!important;grid-template-columns:210px minmax(0,1fr) max-content!important;align-items:center!important;gap:8px!important;padding:0 12px!important}.brand{width:auto!important;min-width:0!important}.brand small{white-space:nowrap}#tabs{min-width:0!important;overflow-x:auto!important;display:flex!important;gap:4px!important}.actions{display:flex!important;position:static!important;align-items:center!important;justify-content:flex-end!important;gap:5px!important;padding:0!important;white-space:nowrap!important}.actions>button,.actions .print-wrap button,#hvLangSelect{font-size:8px!important;padding:6px 7px!important;height:29px!important;white-space:nowrap!important}.print-wrap{position:relative!important;top:auto!important;right:auto!important;z-index:300!important;display:block!important}.print-menu{right:0!important;top:34px!important;z-index:1800!important}#hvLangSelect{width:54px!important;border:1px solid #ffffff55!important;border-radius:7px!important;background:#173f58!important;color:#fff!important;outline:none!important;cursor:pointer!important}#hvLangSelect option{color:#17324a;background:#fff}@media(max-width:1450px){header{grid-template-columns:185px minmax(0,1fr) max-content!important}.actions>button,.actions .print-wrap button,#hvLangSelect,#tabs button{font-size:7.2px!important;padding:5px!important}.brand b{font-size:14px!important}.brand small{font-size:7.5px!important}}@media(max-width:1180px){header{grid-template-columns:160px minmax(0,1fr) max-content!important}.right{display:none!important}main{grid-template-columns:220px minmax(0,1fr)!important}}@media print{.print-page::before{content:none!important}.hvWM{display:block!important;position:absolute!important;left:50%!important;top:48%!important;transform:translate(-50%,-50%) rotate(-28deg)!important;font-size:34pt!important;font-weight:800!important;letter-spacing:.08em!important;color:rgba(16,54,80,.14)!important;white-space:nowrap!important;z-index:10!important;pointer-events:none!important}.print-page svg{position:relative!important;z-index:1!important}.print-page h1,.print-page .psub,.print-footer{position:relative!important;z-index:11!important}}`;document.head.appendChild(s);}
function init(){styles();cleanHeader();applyLanguage();const svg=$('#topologySvg');if(svg){new MutationObserver(()=>{patchImage();setTimeout(applyLanguage,0);}).observe(svg,{childList:true,subtree:true});svg.addEventListener('click',()=>setTimeout(applyLanguage,0));}$('#tabs')?.addEventListener('click',()=>setTimeout(applyLanguage,0));window.addEventListener('beforeprint',ensurePrint);window.addEventListener('afterprint',()=>{const d=$('#printDeck');if(d&&d.dataset.auto==='1'){d.innerHTML='';delete d.dataset.auto;}});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();